/*
 * This class generated by Claude Code (Opus 4.8)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.xmission.trevin.android.tangram.data;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

/**
 * Regression test for a real "Number 8" solve that was wrongly reported as
 * not matching.  The player's arrangement (captured from the debug log) and
 * the goal from {@code assets/puzzles-numbers.json} are congruent silhouettes,
 * but the "8" is a figure-8 that touches itself at the waist; the boundary
 * tracing must handle that pinch consistently for the two layouts to match.
 *
 * @author Claude Opus 4.8
 */
public class Number8DiagnosticTest {

    private static TangramPiece place(TangramPiece p, float rot,
            float xa, float xb, float ya, float yb) {
        p.setRotation(rot);
        p.setPosition(new ImmutableTPoint(xa, xb, ya, yb));
        return p;
    }

    @Test
    public void testFigureEightSolveMatchesGoal() {
        // Player's placement, from the debug log.
        TPolygon player = new TPolygon();
        player.merge(place(new TangramLargeTriangle(), 90, 11, 0, 8, 0));
        player.merge(place(new TangramSquare(), 0, 7, -3, 20, -3));
        player.merge(place(new TangramLargeTriangle(), 270, 3, -6, 8, 0));
        player.merge(place(new TangramSmallTriangle(), 315, 7, -4, -4, -10));
        player.merge(place(new TangramSmallTriangle(), 225, 7, 2, -4, -8));
        player.merge(place(new TangramMediumTriangle(), 270, 7, -8, -4, -6));
        player.merge(place(new TangramParallelogram(), 315, 7, 0, -4, -3));

        // Goal "Number 8" from assets/puzzles-numbers.json.
        TPolygon goal = new TPolygon();
        goal.merge(place(new TangramLargeTriangle(), 90, 4, 3, 0, 6));
        goal.merge(place(new TangramSquare(), 0, 0, 0, 12, 3));
        goal.merge(place(new TangramLargeTriangle(), -90, -4, -3, 0, 6));
        goal.merge(place(new TangramParallelogram(), -45, 0, 3, -12, 3));
        goal.merge(place(new TangramMediumTriangle(), -90, 0, -5, -12, 0));
        goal.merge(place(new TangramSmallTriangle(), -45, 0, -1, -12, -4));
        goal.merge(place(new TangramSmallTriangle(), -135, 0, 5, -12, -2));

        assertTrue("player:\n" + player.describeLoops()
                        + "goal:\n" + goal.describeLoops(),
                player.isIdenticalTo(goal));
    }
}