/*
 * This class generated by Claude Code (Opus 4.8)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.xmission.trevin.android.tangram.data;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import com.xmission.trevin.android.tangram.R;
import com.xmission.trevin.android.tangram.exception.DisconnectedException;
import com.xmission.trevin.android.tangram.exception.ExtraPieceException;
import com.xmission.trevin.android.tangram.exception.InvalidPuzzleException;
import com.xmission.trevin.android.tangram.exception.MissingPieceException;
import com.xmission.trevin.android.tangram.exception.OverlappingPiecesException;
import com.xmission.trevin.android.tangram.exception.PieceNotTouchingException;
import com.xmission.trevin.android.tangram.exception.TangramException;

import org.json.JSONArray;
import org.json.JSONObject;
import org.json.JSONTokener;
import org.junit.Test;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;

/**
 * JVM tests that exercise {@link TangramPuzzle}'s JSON constructor and its
 * validation against real files: every puzzle shipped in the app's asset
 * library must validate, and the hand-crafted bad puzzles under
 * {@code src/test/resources/puzzles/} must each be rejected with the
 * appropriate {@link TangramException}.
 *
 * <p>These require a real {@code org.json} implementation on the test
 * classpath (the android.jar stub throws &ldquo;not mocked&rdquo;), added as a
 * {@code testImplementation} dependency.</p>
 *
 * @author Claude Opus 4.8
 */
public class TangramPuzzleLibraryTests {

    // ---- helpers ----------------------------------------------------------

    /** Locate the app module's {@code src/main/assets} directory, whether
     * the tests run with the working directory at the module or repo root. */
    private static File assetsDir() {
        for (String base : new String[] {
                "src/main/assets", "app/src/main/assets" }) {
            File dir = new File(base);
            if (dir.isDirectory())
                return dir;
        }
        throw new AssertionError("Could not locate src/main/assets");
    }

    private static String readAll(InputStream in) throws Exception {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        byte[] buffer = new byte[4096];
        int n;
        while ((n = in.read(buffer)) >= 0)
            out.write(buffer, 0, n);
        return out.toString(StandardCharsets.UTF_8);
    }

    /** Read a bad-puzzle fixture from {@code src/test/resources/puzzles/}. */
    private static JSONObject fixture(String name) throws Exception {
        try (InputStream in = TangramPuzzleLibraryTests.class
                .getResourceAsStream("/puzzles/" + name)) {
            assertNotNull("fixture /puzzles/" + name + " not found", in);
            return new JSONObject(readAll(in));
        }
    }

    /** Construct a puzzle expected to be invalid and return its errors. */
    private static List<TangramException> rejectionErrors(String fixtureName)
            throws Exception {
        JSONObject json = fixture(fixtureName);
        try {
            new TangramPuzzle(json);
            fail(fixtureName + " should have been rejected as invalid");
            return null; // unreachable
        } catch (InvalidPuzzleException e) {
            return e.getValidationErrors();
        }
    }

    private static boolean hasError(
            List<TangramException> errors,
            Class<? extends TangramException> type) {
        if (errors != null)
            for (TangramException e : errors)
                if (type.isInstance(e))
                    return true;
        return false;
    }

    // ---- the shipped library ---------------------------------------------

    /**
     * Every puzzle in every {@code assets/puzzles-*.json} file must pass
     * validation (the constructor throws {@link InvalidPuzzleException}
     * otherwise).
     */
    @Test
    public void testAllLibraryPuzzlesAreValid() throws Exception {
        File[] files = assetsDir().listFiles(
                (dir, name) -> name.matches("puzzles-.*\\.json"));
        assertNotNull("no puzzle asset files found", files);
        assertTrue("no puzzle asset files found", files.length > 0);

        int validated = 0;
        for (File file : files) {
            String content = Files.readString(file.toPath());
            Object root = new JSONTokener(content).nextValue();
            JSONArray puzzles = (root instanceof JSONArray)
                    ? (JSONArray) root
                    : new JSONArray().put(root);
            for (int i = 0; i < puzzles.length(); i++) {
                JSONObject json = puzzles.getJSONObject(i);
                try {
                    new TangramPuzzle(json);
                    validated++;
                } catch (InvalidPuzzleException e) {
                    fail("Puzzle \"" + json.optString("name", "?")
                            + "\" in " + file.getName()
                            + " failed validation: " + e.getMessage());
                }
            }
        }
        assertTrue("expected at least one library puzzle", validated > 0);
    }

    // ---- the bad puzzles --------------------------------------------------

    @Test
    public void testOverlappingFixtureRejected() throws Exception {
        List<TangramException> errors = rejectionErrors("overlapping.json");
        assertTrue(hasError(errors, OverlappingPiecesException.class));
        // There should be two overlaps in this puzzle
        assertEquals("Number of validation errors", 2, errors.size());
        if ((errors.get(0) instanceof OverlappingPiecesException ope1) &&
                (errors.get(1) instanceof OverlappingPiecesException ope2)) {
            // We expect the small triangle to be overlapping
            // the large triangle and the square, but it
            // doesn't matter what order these are reported.
            // So we compare a set of sets.
            Set<Set<Integer>> expectedIds = Set.of(
                    Set.of(R.string.PieceNameSmallTriangle,
                            R.string.PieceNameLargeTriangle),
                    Set.of(R.string.PieceNameSmallTriangle,
                            R.string.PieceNameSquare));
            Set<Set<Integer>> actualIds = Set.of(
                    ope1.getPieceIds(), ope2.getPieceIds());
            assertEquals("ID's of the names of overlapping pieces",
                    expectedIds, actualIds);
        }
    }

    @Test
    public void testNotTouchingFixtureRejected() throws Exception {
        List<TangramException> errors = rejectionErrors("not-touching.json");
        assertTrue(hasError(errors, PieceNotTouchingException.class));
        assertEquals("Number of validation errors", 1, errors.size());
        if (errors.get(0) instanceof PieceNotTouchingException pne) {
            assertEquals("ID of the name of the piece",
                    R.string.PieceNameSmallTriangle, pne.getPieceId());
        }
    }

    @Test
    public void testDisconnectedFixtureRejected() throws Exception {
        List<TangramException> errors = rejectionErrors("disconnected.json");
        assertTrue(hasError(errors, DisconnectedException.class));
        assertEquals("Number of validation errors", 1, errors.size());
        if (errors.get(0) instanceof DisconnectedException de) {
            // We expect both large triangles in one group and all other
            // pieces in the other.  It doesn't matter which group is which.
            Set<Integer> expectedGroupA = Set.of(
                    R.string.PieceNameLargeTriangle);
            // Make sure multi-item sets are sorted for ease of reading
            Set<Integer> expectedGroupB = new TreeSet<>(Set.of(
                    R.string.PieceNameMediumTriangle,
                    R.string.PieceNameParallelogram,
                    R.string.PieceNameSquare,
                    R.string.PieceNameSmallTriangle));
            Set<Integer> smallerSet, largerSet;
            if (de.getGroup1Ids().size() < de.getGroup2Ids().size()) {
                    smallerSet = new TreeSet<>(de.getGroup1Ids());
                    largerSet = new TreeSet<>(de.getGroup2Ids());
            } else {
                smallerSet = new TreeSet<>(de.getGroup2Ids());
                largerSet = new TreeSet<>(de.getGroup1Ids());
            }
            assertEquals("ID's of the names of pieces in the smaller group",
                    expectedGroupA, smallerSet);
            assertEquals("ID's of the names of pieces in the larger group",
                    expectedGroupB, largerSet);
        }
    }

    @Test
    public void testMissingPieceFixtureRejected() throws Exception {
        List<TangramException> errors = rejectionErrors("missing-piece.json");
        assertTrue(hasError(errors, MissingPieceException.class));
        assertEquals("Number of validation errors", 1, errors.size());
        if (errors.get(0) instanceof MissingPieceException mpe) {
            assertEquals("Number of missing pieces", 1, mpe.getNumMissing());
            assertEquals("ID of the missing piece name",
                    R.string.PieceNameSmallTriangle, mpe.getMissingPieceId());
        }
    }

    @Test
    public void testExtraPieceFixtureRejected() throws Exception {
        List<TangramException> errors = rejectionErrors("extra-piece.json");
        assertTrue(hasError(errors, ExtraPieceException.class));
        assertEquals("Number of validation errors", 1, errors.size());
        if (errors.get(0) instanceof ExtraPieceException epe) {
            assertEquals("Number of extra pieces", 1, epe.getNumExtra());
            assertEquals("ID of the extra piece name",
                    R.string.PieceNameSquare, epe.getExtraPieceId());
        }
    }
}