/*
 * This class generated by Claude Code (Opus 4.8)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.xmission.trevin.android.tangram.data;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

/**
 * Unit tests for {@link TangramPuzzle#snap(TangramPiece)}, covering the
 * free-grid snap (rule 1) and the one-edge snap (rules 2 and 2.4).
 *
 * @author Claude Opus 4.8
 */
public class TangramPuzzleSnapTest {

    private static final double DELTA = 1e-3;

    private static TPoint at(double x, double y) {
        return new ImmutableTPoint((float) x, 0f, (float) y, 0f);
    }

    // ---- rule 1: free snap -------------------------------------------------

    @Test
    public void testEmptyPuzzleSnapsToGridAnd45() {
        TangramPuzzle puzzle = new TangramPuzzle();
        TangramPiece piece = new TangramSmallTriangle();
        piece.setRotation(40f);
        piece.setPosition(at(2.4, 3.6));

        puzzle.snap(piece);

        assertEquals(45f, piece.getRotation(), DELTA);
        assertEquals(2, piece.getPosition().getX(), DELTA);
        assertEquals(4, piece.getPosition().getY(), DELTA);
        // The piece is added to the puzzle by snap().
        assertEquals(1, puzzle.getPieceCount());
    }

    @Test
    public void testDistantPieceSnapsFreelyNotToNeighbor() {
        TangramPuzzle puzzle = new TangramPuzzle();
        puzzle.addPiece(largeTriangleAt(0, 0, 0));

        TangramPiece piece = new TangramSmallTriangle();
        piece.setRotation(7f);
        piece.setPosition(at(100.4, 50.6));
        puzzle.snap(piece);

        assertEquals(0f, piece.getRotation(), DELTA);   // 7° -> nearest 45° = 0
        assertEquals(100, piece.getPosition().getX(), DELTA);
        assertEquals(51, piece.getPosition().getY(), DELTA);
    }

    // ---- rule 2 + 2.4: one-edge snap --------------------------------------

    @Test
    public void testEdgeSnapAlignsMidpointsAndSquaresRotation() {
        // Neighbor large triangle: base edge is horizontal at y = 4,
        // x in [-12, 12], midpoint (0, 4).
        TangramPuzzle puzzle = new TangramPuzzle();
        puzzle.addPiece(largeTriangleAt(0, 0, 0));

        // Moved small triangle dropped just below the base, off by ~4° and a
        // small position offset; only its base-midpoint is near a neighbor
        // feature (the base midpoint), so it should snap midpoint-to-midpoint.
        TangramPiece piece = new TangramSmallTriangle();
        piece.setRotation(4f);
        piece.setPosition(at(0.4, 1.7));
        puzzle.snap(piece);

        assertEquals(0f, piece.getRotation(), DELTA);
        assertEquals(0, piece.getPosition().getX(), DELTA);
        assertEquals(2, piece.getPosition().getY(), DELTA);
    }

    @Test
    public void testEdgeSnapKeepsExactQuadraticFieldPosition() {
        // Neighbor square: its top edge is horizontal at y = -3√2, so aligning
        // to it must keep the irrational coordinate exact in Q[√2].
        TangramPuzzle puzzle = new TangramPuzzle();
        TangramPiece square = new TangramSquare();
        square.setRotation(0f);
        square.setPosition(ImmutableTPoint.ORIGIN);
        puzzle.addPiece(square);

        TangramPiece piece = new TangramSmallTriangle();
        piece.setRotation(3f);
        piece.setPosition(at(0.3, -6.0));
        puzzle.snap(piece);

        assertEquals(0f, piece.getRotation(), DELTA);
        // Expected centroid = (0, -2 - 3√2): coefficients (0,0,-2,-3), exact.
        TPoint pos = piece.getPosition();
        assertEquals(0, pos.getXa(), DELTA);
        assertEquals(0, pos.getXb(), DELTA);
        assertEquals(-2, pos.getYa(), DELTA);
        assertEquals(-3, pos.getYb(), DELTA);
    }

    @Test
    public void testEdgeSnapPerpendicularOnlyWhenNoFeatureAligns() {
        // Neighbor large triangle base at y = 4, x in [-12, 12].
        TangramPuzzle puzzle = new TangramPuzzle();
        puzzle.addPiece(largeTriangleAt(0, 0, 0));

        // Moved small triangle overlaps the base (x in [3, 15]) but no
        // endpoint/midpoint is within a unit of a neighbor feature, so only
        // the perpendicular (y) snap applies; the along-edge (x) position
        // stays where it was dropped.
        TangramPiece piece = new TangramSmallTriangle();
        piece.setRotation(0f);
        piece.setPosition(at(9, 1.7));
        puzzle.snap(piece);

        assertEquals(0f, piece.getRotation(), DELTA);
        assertEquals(9, piece.getPosition().getX(), DELTA);   // unchanged
        assertEquals(2, piece.getPosition().getY(), DELTA);   // flush at y=4
    }

    // ---- rule 2.1: two-edge corner fit -----------------------------------

    @Test
    public void testTwoEdgeCornerFit() {
        // Neighbor square occupies x,y in [-3√2, 3√2].  A second square
        // dropped just off the corner to its right should corner-fit so its
        // left edge is collinear with the neighbor's right edge and its top
        // edge collinear with the neighbor's top edge: centre at (6√2, 0).
        double sqrt2 = Math.sqrt(2);
        TangramPuzzle puzzle = new TangramPuzzle();
        TangramPiece neighbor = new TangramSquare();
        neighbor.setPosition(ImmutableTPoint.ORIGIN);
        puzzle.addPiece(neighbor);

        TangramPiece moved = new TangramSquare();
        moved.setRotation(2f);
        moved.setPosition(at(6 * sqrt2 + 0.3, 0.2));
        puzzle.snap(moved);

        assertEquals(0f, moved.getRotation(), 1e-2);
        assertEquals(6 * sqrt2, moved.getPosition().getX(), 1e-2);
        assertEquals(0, moved.getPosition().getY(), 1e-2);
    }

    @Test
    public void testCornerFitSmallTriangleIntoLargeTriangleCorner() {
        // Neighbor large triangle: base y=4 (x in [-12,12]) and right leg from
        // (12,4) up to the apex (0,-8).  A small triangle dropped near the
        // right corner should corner-fit: base flush with the base and right
        // leg flush with the leg, putting its base-right vertex on (12,4) — so
        // its centroid lands at (6,2).  (A 45° second edge, rule 2.1.)
        TangramPuzzle puzzle = new TangramPuzzle();
        puzzle.addPiece(largeTriangleAt(0, 0, 0));

        TangramPiece moved = new TangramSmallTriangle();
        moved.setRotation(0f);
        moved.setPosition(at(6.4, 1.8));
        puzzle.snap(moved);

        assertEquals(0f, moved.getRotation(), 1e-2);
        assertEquals(6, moved.getPosition().getX(), 1e-2);
        assertEquals(2, moved.getPosition().getY(), 1e-2);
    }

    // ---- rule 3: vertex-only contact -------------------------------------

    @Test
    public void testVertexSnapsToNeighborVertexAt15Degrees() {
        // Large triangle apex is (0,-8).  A small triangle dropped tip-to-tip
        // near it, rotated ~13° (so no edges are parallel), should snap its
        // rotation to 15° and land its apex exactly on (0,-8).
        TangramPuzzle puzzle = new TangramPuzzle();
        puzzle.addPiece(largeTriangleAt(0, 0, 0));

        TangramPiece moved = new TangramSmallTriangle();
        moved.setRotation(13f);
        moved.setPosition(at(-0.6, -4.3));
        puzzle.snap(moved);

        assertEquals(15f, moved.getRotation(), 1e-2);
        TPoint apex = moved.getVertices()[0];
        assertEquals(0, apex.getX(), 1e-2);
        assertEquals(-8, apex.getY(), 1e-2);
    }

    @Test
    public void testVertexSnapsOntoNeighborEdge() {
        // A small triangle dropped so only its apex is near the middle of the
        // large triangle's base (not near a vertex or the base midpoint),
        // rotated ~20°, should snap to 15° and drop its apex onto the base
        // line (y=4), keeping its along-base position.
        TangramPuzzle puzzle = new TangramPuzzle();
        puzzle.addPiece(largeTriangleAt(0, 0, 0));

        TangramPiece moved = new TangramSmallTriangle();
        moved.setRotation(20f);
        moved.setPosition(at(3.6319, 8.2588));
        puzzle.snap(moved);

        assertEquals(15f, moved.getRotation(), 1e-2);
        TPoint apex = moved.getVertices()[0];
        assertEquals(4, apex.getY(), 1e-2);              // lies on the base
        assertEquals(4.667, apex.getX(), 1e-2);          // along-base unchanged
    }

    // ---- edge-through-neighbor-vertex snap ---------------------------------

    @Test
    public void testEdgeSnapsToNeighborVertex() {
        // A large triangle with its right leg running up to the vertex at
        // (12, -2).  A medium triangle rotated 90° has a vertical left edge;
        // placed at x=15 that edge sits at x = 15 - 2√2 ≈ 12.17, leaving a
        // ~0.17 gap from the vertex (no edge overlap, no vertex-vertex touch),
        // which used to fall through to a free grid snap.
        TangramPuzzle puzzle = new TangramPuzzle();
        TangramPiece large = largeTriangleAt(0, 0, -6);
        puzzle.addPiece(large);

        TangramPiece medium = new TangramMediumTriangle();
        medium.setRotation(90f);
        medium.setPosition(at(15, 3));
        puzzle.snap(medium);

        // Rotation (already a 45° multiple) is preserved, and the piece is
        // shifted so its edge passes through the vertex, closing the gap.
        assertEquals(90f, medium.getRotation(), DELTA);
        assertEquals(12 + 2 * Math.sqrt(2), medium.getPosition().getX(), 1e-2);
        assertEquals(3, medium.getPosition().getY(), 1e-2);
        assertTrue("edge should now touch the neighbor vertex",
                medium.touches(large));
    }

    @Test
    public void testSnapDoesNotDuplicateAnAlreadyPresentPiece() {
        TangramPuzzle puzzle = new TangramPuzzle();
        TangramPiece piece = new TangramSmallTriangle();
        piece.setPosition(at(0, 0));
        puzzle.addPiece(piece);

        puzzle.snap(piece);

        assertEquals(1, puzzle.getPieceCount());
        assertTrue(puzzle.getPiece(0) == piece);
    }

    /** A large triangle at the given rotation (deg) and centroid (x, y). */
    private static TangramPiece largeTriangleAt(float rotation, double x, double y) {
        TangramPiece t = new TangramLargeTriangle();
        t.setRotation(rotation);
        t.setPosition(at(x, y));
        return t;
    }
}