/*
 * This class generated by Claude Code (Opus 4.8)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.xmission.trevin.android.tangram.data;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import com.xmission.trevin.android.tangram.R;
import com.xmission.trevin.android.tangram.exception.DisconnectedException;
import com.xmission.trevin.android.tangram.exception.ExtraPieceException;
import com.xmission.trevin.android.tangram.exception.InvalidPuzzleException;
import com.xmission.trevin.android.tangram.exception.MissingPieceException;
import com.xmission.trevin.android.tangram.exception.OverlappingPiecesException;
import com.xmission.trevin.android.tangram.exception.PieceNotTouchingException;
import com.xmission.trevin.android.tangram.exception.TangramException;

import org.json.JSONException;
import org.json.JSONObject;
import org.junit.Test;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;

/**
 * JVM tests that exercise {@link TangramPuzzle}'s JSON constructor and
 * its validation against test files: the basic square (correctly formed)
 * must validate, and bad puzzles must be rejected with the appropriate
 * {@link TangramException}.
 *
 * @author Claude Opus 4.8
 */
public class TangramPuzzleValidationTests {

    // ---- helpers ----------------------------------------------------------

    /**
     * Read the contents of an {@code InputStream} into a {@code String}.
     *
     * @param in the {@code InputStream} to read
     *
     * @return the contents of the {@code InputStream} as a {@code String}
     */
    private static String readAll(InputStream in) throws IOException {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        byte[] buffer = new byte[4096];
        int n;
        while ((n = in.read(buffer)) >= 0)
            out.write(buffer, 0, n);
        return out.toString(StandardCharsets.UTF_8);
    }

    /**
     * Read a puzzle from {@code src/test/resources/puzzles/}.
     *
     * @param name the name of the puzzle file, which should contain
     * a single puzzle as a JSON object.
     *
     * @throws IOException if the file cannot be read
     * @throws JSONException if the file contains invalid JSON
     */
    private static JSONObject fixture(String name)
            throws IOException, JSONException {
        try (InputStream in = TangramPuzzleValidationTests.class
                .getResourceAsStream("/puzzles/" + name)) {
            assertNotNull("fixture /puzzles/" + name + " not found", in);
            return new JSONObject(readAll(in));
        }
    }

    /**
     * Construct a puzzle expected to be invalid and return its errors.
     *
     * @param fixtureName the name of the bad puzzle file to test
     *
     * @return the list of errors thrown by the
     * {@link com.xmission.trevin.android.tangram.data.TangramPuzzle#TangramPuzzle(JSONObject)
     * TangramPuzzle(json)} constructor
     *
     * @throws IOException if the file cannot be read
     * @throws JSONException if the file contains invalid JSON
     */
    private static List<TangramException> rejectionErrors(String fixtureName)
            throws IOException, JSONException {
        JSONObject json = fixture(fixtureName);
        try {
            new TangramPuzzle(json);
            fail(fixtureName + " should have been rejected as invalid");
            return null; // unreachable
        } catch (InvalidPuzzleException e) {
            return e.getValidationErrors();
        }
    }

    /**
     * Check whether a list of {@link TangramException}s
     * contains an expected exception class.
     *
     * @param errors the list of exceptions thrown by the constructor.
     * @param type the expected exception class
     *
     * @return {@code true} if {@code errors} contains at least one
     * exception of the given {@code type}, {@code false} otherwise.
     */
    private static boolean hasError(
            List<TangramException> errors,
            Class<? extends TangramException> type) {
        if (errors != null)
            for (TangramException e : errors)
                if (type.isInstance(e))
                    return true;
        return false;
    }

    // ---- the valid puzzle ---------------------------------------------

    /**
     * The valid square file must pass validation.
     */
    @Test
    public void testValidPuzzle() throws Exception {
        JSONObject json = fixture("square.json");
        TangramPuzzle puzzle = new TangramPuzzle(json);
    }

    // ---- the bad puzzles --------------------------------------------------

    /**
     * Test a puzzle where at least one piece overlaps another.
     */
    @Test
    public void testOverlappingFixtureRejected() throws Exception {
        List<TangramException> errors = rejectionErrors("overlapping.json");
        assertTrue(hasError(errors, OverlappingPiecesException.class));
        // There should be two overlaps in this puzzle
        assertEquals("Number of validation errors", 2, errors.size());
        if ((errors.get(0) instanceof OverlappingPiecesException ope1) &&
                (errors.get(1) instanceof OverlappingPiecesException ope2)) {
            // We expect the small triangle to be overlapping
            // the large triangle and the square, but it
            // doesn't matter what order these are reported.
            // So we compare a set of sets.
            Set<Set<Integer>> expectedIds = Set.of(
                    Set.of(R.string.PieceNameSmallTriangle,
                            R.string.PieceNameLargeTriangle),
                    Set.of(R.string.PieceNameSmallTriangle,
                            R.string.PieceNameSquare));
            Set<Set<Integer>> actualIds = Set.of(
                    ope1.getPieceIds(), ope2.getPieceIds());
            assertEquals("ID's of the names of overlapping pieces",
                    expectedIds, actualIds);
        }
    }

    /**
     * Test a puzzle where at least one piece is not touching any others.
     */
    @Test
    public void testNotTouchingFixtureRejected() throws Exception {
        List<TangramException> errors = rejectionErrors("not-touching.json");
        assertTrue(hasError(errors, PieceNotTouchingException.class));
        assertEquals("Number of validation errors", 1, errors.size());
        if (errors.get(0) instanceof PieceNotTouchingException pne) {
            assertEquals("ID of the name of the piece",
                    R.string.PieceNameSmallTriangle, pne.getPieceId());
        }
    }

    /**
     * Test a puzzle where a group of at least two pieces is not touching
     * another group of at least two pieces.  This is a distinct case from
     * a single piece not touching any others.
     */
    @Test
    public void testDisconnectedFixtureRejected() throws Exception {
        List<TangramException> errors = rejectionErrors("disconnected.json");
        assertTrue(hasError(errors, DisconnectedException.class));
        assertEquals("Number of validation errors", 1, errors.size());
        if (errors.get(0) instanceof DisconnectedException de) {
            // We expect both large triangles in one group and all other
            // pieces in the other.  It doesn't matter which group is which.
            Set<Integer> expectedGroupA = Set.of(
                    R.string.PieceNameLargeTriangle);
            // Make sure multi-item sets are sorted for ease of reading
            Set<Integer> expectedGroupB = new TreeSet<>(Set.of(
                    R.string.PieceNameMediumTriangle,
                    R.string.PieceNameParallelogram,
                    R.string.PieceNameSquare,
                    R.string.PieceNameSmallTriangle));
            Set<Integer> smallerSet, largerSet;
            if (de.getGroup1Ids().size() < de.getGroup2Ids().size()) {
                    smallerSet = new TreeSet<>(de.getGroup1Ids());
                    largerSet = new TreeSet<>(de.getGroup2Ids());
            } else {
                smallerSet = new TreeSet<>(de.getGroup2Ids());
                largerSet = new TreeSet<>(de.getGroup1Ids());
            }
            assertEquals("ID's of the names of pieces in the smaller group",
                    expectedGroupA, smallerSet);
            assertEquals("ID's of the names of pieces in the larger group",
                    expectedGroupB, largerSet);
        }
    }

    /**
     * Test a puzzle which is missing at least one piece.  It&rsquo;s
     * possible for a puzzle to have both missing and extra pieces
     * of different types.
     */
    @Test
    public void testMissingPieceFixtureRejected() throws Exception {
        List<TangramException> errors = rejectionErrors("missing-piece.json");
        assertTrue(hasError(errors, MissingPieceException.class));
        assertEquals("Number of validation errors", 1, errors.size());
        if (errors.get(0) instanceof MissingPieceException mpe) {
            assertEquals("Number of missing pieces", 1, mpe.getNumMissing());
            assertEquals("ID of the missing piece name",
                    R.string.PieceNameSmallTriangle, mpe.getMissingPieceId());
        }
    }

    /**
     * Test a puzzle which has too many instances of at least one type of
     * piece.  It&rsquo;s possible for a puzzle to have both missing and
     * extra pieces of different types.
     */
    @Test
    public void testExtraPieceFixtureRejected() throws Exception {
        List<TangramException> errors = rejectionErrors("extra-piece.json");
        assertTrue(hasError(errors, ExtraPieceException.class));
        assertEquals("Number of validation errors", 1, errors.size());
        if (errors.get(0) instanceof ExtraPieceException epe) {
            assertEquals("Number of extra pieces", 1, epe.getNumExtra());
            assertEquals("ID of the extra piece name",
                    R.string.PieceNameSquare, epe.getExtraPieceId());
        }
    }
}