/*
 * This class generated by Claude Code (Opus 4.8)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.xmission.trevin.android.tangram.data;

import static com.xmission.trevin.android.tangram.data.ImmutableTPoint.ORIGIN;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

/**
 * Unit tests for {@link TEdge}, the snapping geometry foundation.
 *
 * @author Claude Opus 4.8
 */
public class TEdgeTest {

    private static final double DELTA = 1e-4;
    private static final double SQRT2 = Math.sqrt(2);

    /** Convenience: an integer-coefficient (b = 0) point (x, y). */
    private static TPoint pointAt(double x, double y) {
        return new ImmutableTPoint((float) x, 0f, (float) y, 0f);
    }

    // ---- length / direction ------------------------------------------------

    @Test
    public void testLengthAndAngle() {
        TEdge horizontal = new TEdge(ORIGIN, pointAt(6, 0));
        assertEquals(6, horizontal.length(), DELTA);
        assertEquals(0, horizontal.angleDegrees(), DELTA);

        TEdge vertical = new TEdge(ORIGIN, pointAt(0, 6));
        assertEquals(6, vertical.length(), DELTA);
        assertEquals(90, vertical.angleDegrees(), DELTA);

        TEdge diagonal = new TEdge(ORIGIN, pointAt(6, 6));
        assertEquals(6 * SQRT2, diagonal.length(), DELTA);
        assertEquals(45, diagonal.angleDegrees(), DELTA);

        // atan2 negatives must normalize to [0, 360).
        assertEquals(180, new TEdge(ORIGIN, pointAt(-6, 0)).angleDegrees(), DELTA);
        assertEquals(270, new TEdge(ORIGIN, pointAt(0, -6)).angleDegrees(), DELTA);
        assertEquals(315, new TEdge(ORIGIN, pointAt(6, -6)).angleDegrees(), DELTA);
    }

    @Test
    public void testMidpointIsExactInQuadraticField() {
        // Endpoints with both a and b coefficients: midpoint averages them.
        TEdge e = new TEdge(new ImmutableTPoint(0, 0, 0, 0),
                new ImmutableTPoint(6, 2, 4, 2));
        TPoint mid = e.midpoint();
        assertEquals(3, mid.getXa(), DELTA);
        assertEquals(1, mid.getXb(), DELTA);
        assertEquals(2, mid.getYa(), DELTA);
        assertEquals(1, mid.getYb(), DELTA);
        assertEquals(3 + SQRT2, mid.getX(), DELTA);
        assertEquals(2 + SQRT2, mid.getY(), DELTA);
    }

    // ---- parallelism -------------------------------------------------------

    @Test
    public void testLineAngleDifferenceTreatsEdgesAsUndirected() {
        TEdge a = new TEdge(ORIGIN, pointAt(6, 0));
        // Opposite direction is still parallel (difference 0).
        assertEquals(0,
                a.lineAngleDifference(new TEdge(pointAt(6, 0), ORIGIN)), DELTA);
        // Perpendicular.
        assertEquals(90,
                a.lineAngleDifference(new TEdge(ORIGIN, pointAt(0, 6))), DELTA);
        // 45 degrees.
        assertEquals(45,
                a.lineAngleDifference(new TEdge(ORIGIN, pointAt(6, 6))), DELTA);
    }

    @Test
    public void testIsNearlyParallel() {
        TEdge a = new TEdge(ORIGIN, pointAt(6, 0));
        // ~5.7 degrees: within a 7.5-degree tolerance.
        assertTrue(a.isNearlyParallel(new TEdge(ORIGIN, pointAt(6, 0.6)), 7.5));
        // ~9.5 degrees: outside it.
        assertFalse(a.isNearlyParallel(new TEdge(ORIGIN, pointAt(6, 1)), 7.5));
        // Anti-parallel is parallel.
        assertTrue(a.isNearlyParallel(new TEdge(pointAt(6, 0), ORIGIN), 7.5));
    }

    // ---- projection / distances -------------------------------------------

    @Test
    public void testProjectionFraction() {
        TEdge a = new TEdge(ORIGIN, pointAt(6, 0));
        assertEquals(0.0, a.projectionFraction(pointAt(0, 5)), DELTA);
        assertEquals(1.0, a.projectionFraction(pointAt(6, -5)), DELTA);
        assertEquals(0.5, a.projectionFraction(pointAt(3, 2)), DELTA);
        assertEquals(-1.0 / 3, a.projectionFraction(pointAt(-2, 0)), DELTA);
        assertEquals(4.0 / 3, a.projectionFraction(pointAt(8, 3)), DELTA);
    }

    @Test
    public void testNearestPointAndDistanceClampToSegment() {
        TEdge a = new TEdge(ORIGIN, pointAt(6, 0));

        // Perpendicular foot within the segment.
        TPoint near = a.nearestPointTo(pointAt(3, 2));
        assertEquals(3, near.getX(), DELTA);
        assertEquals(0, near.getY(), DELTA);
        assertEquals(2, a.distanceToPoint(pointAt(3, 2)), DELTA);

        // Beyond the start: clamps to the start endpoint.
        assertEquals(2, a.distanceToPoint(pointAt(-2, 0)), DELTA);
        assertEquals(0, a.nearestPointTo(pointAt(-2, 0)).getX(), DELTA);

        // Beyond the end: clamps to the end endpoint.
        assertEquals(Math.sqrt(13), a.distanceToPoint(pointAt(8, 3)), DELTA);
        assertEquals(6, a.nearestPointTo(pointAt(8, 3)).getX(), DELTA);
    }

    @Test
    public void testPerpendicularDistanceIgnoresEndpoints() {
        TEdge a = new TEdge(ORIGIN, pointAt(6, 0));
        // On the line, beyond the segment: still zero from the infinite line.
        assertEquals(0, a.perpendicularDistanceToLine(pointAt(100, 0)), DELTA);
        // Off the line, beyond the segment: the perpendicular offset only.
        assertEquals(3, a.perpendicularDistanceToLine(pointAt(8, 3)), DELTA);
    }

    // ---- overlap -----------------------------------------------------------

    @Test
    public void testOverlapLength() {
        TEdge a = new TEdge(ORIGIN, pointAt(6, 0)); // length 6

        // Identical edge: full overlap.
        assertEquals(6, a.overlapLength(new TEdge(ORIGIN, pointAt(6, 0))), DELTA);
        // Half-shifted: 3 units of overlap.
        assertEquals(3, a.overlapLength(new TEdge(pointAt(3, 0), pointAt(9, 0))), DELTA);
        // Fully contained: overlap is the shorter edge's extent.
        assertEquals(2, a.overlapLength(new TEdge(pointAt(2, 0), pointAt(4, 0))), DELTA);
        // End-to-end contact: zero overlap (a vertex case, not an edge case).
        assertEquals(0, a.overlapLength(new TEdge(pointAt(6, 0), pointAt(10, 0))), DELTA);
        // Gap along the direction: negative.
        assertTrue(a.overlapLength(new TEdge(pointAt(8, 0), pointAt(12, 0))) < 0);
    }

    @Test
    public void testOverlapLengthIsAlongDirectionOnly() {
        // A parallel edge offset perpendicularly still reports its
        // along-direction overlap; perpendicular separation is a separate
        // check (perpendicularDistanceToLine).
        TEdge a = new TEdge(ORIGIN, pointAt(6, 0));
        assertEquals(4, a.overlapLength(new TEdge(pointAt(1, 2), pointAt(5, 2))), DELTA);
    }

    // ---- piece edges -------------------------------------------------------

    @Test
    public void testPieceGetEdges() {
        // Small triangle at its default transform: (0,-4), (6,2), (-6,2).
        TangramPiece piece = new TangramSmallTriangle();
        TEdge[] edges = piece.getEdges();
        assertEquals(3, edges.length);

        // Edge 1 is the hypotenuse (the base), horizontal, length 12.
        assertEquals(12, edges[1].length(), DELTA);
        assertEquals(180, edges[1].angleDegrees(), DELTA);

        // The two legs are equal (6√2) and mutually perpendicular.
        assertEquals(6 * SQRT2, edges[0].length(), DELTA);
        assertEquals(6 * SQRT2, edges[2].length(), DELTA);
        assertEquals(90, edges[0].lineAngleDifference(edges[2]), DELTA);
    }
}