/*
 * This class generated by Claude Code (Opus 4.8)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.xmission.trevin.android.tangram.data;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

/**
 * @author Claude Opus 4.8
 * @author Trevin Beattie
 */
public class TouchDiagnosticTest {

    private static TangramPiece place(TangramPiece p, float rot,
            float xa, float xb, float ya, float yb) {
        p.setRotation(rot);
        p.setPosition(new ImmutableTPoint(xa, xb, ya, yb));
        return p;
    }

    private static String vs(TangramPiece p) {
        StringBuilder sb = new StringBuilder();
        for (TPoint v : p.getVertices())
            sb.append(String.format("(%.4f,%.4f) ", v.getX(), v.getY()));
        return sb.toString();
    }

    /** Minimum vertex-to-edge distance between two pieces, both directions. */
    private static double minVertexEdge(TangramPiece a, TangramPiece b) {
        double min = Double.POSITIVE_INFINITY;
        for (TPoint v : a.getVertices())
            for (TEdge e : b.getEdges())
                min = Math.min(min, e.distanceToPoint(v));
        for (TPoint v : b.getVertices())
            for (TEdge e : a.getEdges())
                min = Math.min(min, e.distanceToPoint(v));
        return min;
    }

    /**
     * Test puzzle validation for a specific case where the vertices of
     * the large triangles are just touching the edges of the other
     * triangles, i.e. no vertex-to-vertex contact or edge-to-edge overlap.
     */
    @Test
    public void diagnose() {
        TangramPuzzle puzzle = new TangramPuzzle();
        TangramPiece lt1 = place(new TangramLargeTriangle(), 0, 0, 0, -6, 0);
        puzzle.addPiece(lt1);
        TangramPiece square = place(new TangramSquare(), 0, 0, 0, -2, 3);
        puzzle.addPiece(square);
        TangramPiece lt2 = place(new TangramLargeTriangle(), 180, 0, 0, 2, 6);
        puzzle.addPiece(lt2);
        TangramPiece medium = place(new TangramMediumTriangle(), 90, 12, 2, 3, 0);
        puzzle.addPiece(medium);
        TangramPiece small1 = place(new TangramSmallTriangle(), 45, -12, -2, 5, 0);
        puzzle.addPiece(small1);
        TangramPiece small2 = place(new TangramSmallTriangle(), 135, -12, -2, 5, -4);
        puzzle.addPiece(small2);
        TangramPiece para = place(new TangramParallelogram(), 255,
                0.568406f, 0, -23.46979f, 0);
        puzzle.addPiece(para);

        String[] names = {"LT1", "Square", "LT2", "Medium", "Small1", "Small2", "Para"};
        TangramPiece[] pieces = {lt1, square, lt2, medium, small1, small2, para};

        StringBuilder sb = new StringBuilder("\n");
        for (int i = 0; i < pieces.length; i++)
            sb.append(names[i]).append(": ").append(vs(pieces[i])).append("\n");
        sb.append("--- pairwise ---\n");
        for (int i = 0; i < pieces.length; i++)
            for (int j = i + 1; j < pieces.length; j++) {
                double d = minVertexEdge(pieces[i], pieces[j]);
                boolean t = pieces[i].touches(pieces[j]);
                boolean o = pieces[i].overlaps(pieces[j]);
                if (d < 1.0 || t)
                    sb.append(String.format("%s <-> %s : minVE=%.5f touches=%b overlaps=%b%n",
                            names[i], names[j], d, t, o));
            }
        assertTrue("Puzzle failed validation:\n" + sb.toString(),
                puzzle.isValid(false));
    }
}