/*
 * This class generated by Claude Code (Opus 4.8)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.xmission.trevin.android.tangram.data;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import org.json.JSONObject;
import org.junit.Test;

import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;

/**
 * Tests for {@link TPolygon#isIdenticalTo(TPolygon)} using real puzzle
 * fixtures: silhouettes with holes (pinwheel), rotational symmetry, and
 * edge-overlap variation within tolerance (the number 2).
 *
 * @author Claude Opus 4.8
 */
public class TPolygonTest {

    private static TPolygon regionOf(String fixture) throws Exception {
        try (InputStream in = TPolygonTest.class
                .getResourceAsStream("/puzzles/" + fixture)) {
            assertNotNull("fixture /puzzles/" + fixture + " not found", in);
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            byte[] buffer = new byte[4096];
            int n;
            while ((n = in.read(buffer)) >= 0)
                out.write(buffer, 0, n);
            JSONObject json = new JSONObject(
                    out.toString(StandardCharsets.UTF_8.name()));
            return TPolygon.fromPuzzle(new TangramPuzzle(json));
        }
    }

    @Test
    public void testPinwheelHasAHole() throws Exception {
        // Outer outline plus one interior hole.
        assertEquals(2, regionOf("pinwheel.json").loopCount());
    }

    @Test
    public void testNumberTwoIsSolid() throws Exception {
        assertEquals(1, regionOf("two.json").loopCount());
    }

    @Test
    public void testRegionMatchesItself() throws Exception {
        assertTrue(regionOf("pinwheel.json")
                .isIdenticalTo(regionOf("pinwheel.json")));
        assertTrue(regionOf("two.json")
                .isIdenticalTo(regionOf("two.json")));
    }

    @Test
    public void testPinwheelMatchesRotatedCopy() throws Exception {
        // A 180°-rotated pinwheel is the same silhouette (hole and all),
        // and its pieces differ, exercising both the hole handling and
        // piece substitution via the shape's rotational symmetry.
        TPolygon pinwheel = regionOf("pinwheel.json");
        TPolygon rotated = regionOf("pinwheel-rotated.json");
        assertTrue(pinwheel.isIdenticalTo(rotated));
        assertTrue(rotated.isIdenticalTo(pinwheel));
    }

    @Test
    public void testNumberTwoMatchesSquishedVariant() throws Exception {
        // The two large triangles overlap by 3√2 in one and 5 in the other;
        // the resulting edge-length differences are within tolerance.
        TPolygon two = regionOf("two.json");
        TPolygon squished = regionOf("two-squished.json");
        assertTrue(two.isIdenticalTo(squished));
        assertTrue(squished.isIdenticalTo(two));
    }

    @Test
    public void testDifferentSilhouettesDoNotMatch() throws Exception {
        // Different shapes (and different hole counts) must not match.
        assertFalse(regionOf("pinwheel.json")
                .isIdenticalTo(regionOf("two.json")));
        assertFalse(regionOf("two.json")
                .isIdenticalTo(regionOf("pinwheel.json")));
    }
}