/*
 * This class generated by Claude Code (Opus 4.8)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.xmission.trevin.android.tangram.data;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import android.util.Log;

import org.json.JSONException;
import org.json.JSONObject;
import org.junit.Test;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;

/**
 * Tests for {@link TPolygon#isIdenticalTo(TPolygon)} using real puzzle
 * fixtures: silhouettes with holes (pinwheel), rotational symmetry, and
 * edge-overlap variation within tolerance (the number 2).
 *
 * @author Claude Opus 4.8
 */
public class TPolygonTest {

    private static final String LOG_TAG = "TPolygonTest";

    private static TPolygon regionOf(String fixture) {
        try (InputStream in = TPolygonTest.class
                .getResourceAsStream("/puzzles/" + fixture)) {
            assertNotNull("fixture /puzzles/" + fixture + " not found", in);
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            byte[] buffer = new byte[4096];
            int n;
            while ((n = in.read(buffer)) >= 0)
                out.write(buffer, 0, n);
            JSONObject json = new JSONObject(
                    out.toString(StandardCharsets.UTF_8));
            return TPolygon.fromPuzzle(new TangramPuzzle(json));
        } catch (IOException x) {
            Log.e(LOG_TAG, fixture, x);
            fail("I/O error reading /puzzles/" + fixture);
            // Unreachable
            throw new RuntimeException(x);
        } catch (JSONException x) {
            Log.e(LOG_TAG, fixture, x);
            fail("Invalid JSON in /puzzles/" + fixture);
            // Unreachable
            throw new RuntimeException(x);
        }
    }

    @Test
    public void testPinwheelHasAHole() {
        // Outer outline plus one interior hole.
        assertEquals(2, regionOf("pinwheel.json").loopCount());
    }

    @Test
    public void testNumberTwoIsSolid() {
        assertEquals(1, regionOf("two.json").loopCount());
    }

    @Test
    public void testRegionMatchesItself() {
        assertTrue(regionOf("pinwheel.json")
                .isIdenticalTo(regionOf("pinwheel.json")));
        assertTrue(regionOf("two.json")
                .isIdenticalTo(regionOf("two.json")));
    }

    @Test
    public void testPinwheelMatchesRotatedCopy() {
        // A 180°-rotated pinwheel is the same silhouette (hole and all),
        // and its pieces differ, exercising both the hole handling and
        // piece substitution via the shape's rotational symmetry.
        TPolygon pinwheel = regionOf("pinwheel.json");
        TPolygon rotated = regionOf("pinwheel-rotated.json");
        assertTrue(pinwheel.isIdenticalTo(rotated));
        assertTrue(rotated.isIdenticalTo(pinwheel));
    }

    @Test
    public void testNumberTwoMatchesSquishedVariant() {
        // The two large triangles overlap by 3√2 in one and 5 in the other;
        // the resulting edge-length differences are within tolerance.
        TPolygon two = regionOf("two.json");
        TPolygon squished = regionOf("two-squished.json");
        assertTrue(two.isIdenticalTo(squished));
        assertTrue(squished.isIdenticalTo(two));
    }

    @Test
    public void testDifferentSilhouettesDoNotMatch() {
        // Different shapes (and different hole counts) must not match.
        assertFalse(regionOf("pinwheel.json")
                .isIdenticalTo(regionOf("two.json")));
        assertFalse(regionOf("two.json")
                .isIdenticalTo(regionOf("pinwheel.json")));
    }

    @Test
    public void testCandleMatchesReverseOrder() {
        TPolygon candleDown = regionOf("candle-down.json");
        TPolygon candleUp = regionOf("candle-up.json");
        if (!candleUp.isIdenticalTo(candleDown)) {
            Log.i(LOG_TAG, "Polygon of candle built top-down: " + candleDown);
            Log.i(LOG_TAG, "Polygon of candle built bottom-up: " + candleUp);
            fail("Candles built in different directions do not match.");
        }
    }

    @Test
    public void testTouchingVertices1Matches2() {
        TPolygon poly1 = regionOf("touching-vertices-1.json");
        TPolygon poly2 = regionOf("touching-vertices-2.json");
        if (!poly1.isIdenticalTo(poly2)) {
            Log.i(LOG_TAG, "Polygon 1: " + poly1);
            Log.i(LOG_TAG, "Polygon 2: " + poly2);
            fail("Polygons specified in different orders do not match.");
        }
    }

    @Test
    public void testTouchingVertices2Matches3() {
        TPolygon poly2 = regionOf("touching-vertices-2.json");
        TPolygon poly3 = regionOf("touching-vertices-3.json");
        if (!poly2.isIdenticalTo(poly3)) {
            Log.i(LOG_TAG, "Polygon 2: " + poly2);
            Log.i(LOG_TAG, "Polygon 3: " + poly3);
            fail("Polygons specified in different orders do not match.");
        }
    }

    @Test
    public void testTouchingVertices3Matches4() {
        TPolygon poly3 = regionOf("touching-vertices-3.json");
        TPolygon poly4 = regionOf("touching-vertices-4.json");
        if (!poly3.isIdenticalTo(poly4)) {
            Log.i(LOG_TAG, "Polygon 3: " + poly3);
            Log.i(LOG_TAG, "Polygon 4: " + poly4);
            fail("Polygons specified in different orders do not match.");
        }
    }

    @Test
    public void testTouchingVertices1Matches3() {
        TPolygon poly1 = regionOf("touching-vertices-1.json");
        TPolygon poly3 = regionOf("touching-vertices-3.json");
        if (!poly1.isIdenticalTo(poly3)) {
            Log.i(LOG_TAG, "Polygon 1: " + poly1);
            Log.i(LOG_TAG, "Polygon 3: " + poly3);
            fail("Polygons specified in different orders do not match.");
        }
    }

    @Test
    public void testTouchingVertices2Matches4() {
        TPolygon poly2 = regionOf("touching-vertices-2.json");
        TPolygon poly4 = regionOf("touching-vertices-4.json");
        if (!poly2.isIdenticalTo(poly4)) {
            Log.i(LOG_TAG, "Polygon 2: " + poly2);
            Log.i(LOG_TAG, "Polygon 4: " + poly4);
            fail("Polygons specified in different orders do not match.");
        }
    }

    @Test
    public void testTouchingVertices1Matches4() {
        TPolygon poly1 = regionOf("touching-vertices-1.json");
        TPolygon poly4 = regionOf("touching-vertices-4.json");
        if (!poly1.isIdenticalTo(poly4)) {
            Log.i(LOG_TAG, "Polygon 1: " + poly1);
            Log.i(LOG_TAG, "Polygon 4: " + poly4);
            fail("Polygons specified in different orders do not match.");
        }
    }

}