/*
 * This class generated by Claude Code (Opus 4.8)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.xmission.trevin.android.tangram.data;

import android.util.Log;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import java.util.Locale;

/**
 * In-memory holder for a single game the player left in progress, so the
 * main menu can offer to resume it.
 *
 * <p>This is a runtime-only singleton: the saved game survives activity
 * restarts (e.g. orientation changes) because the process&mdash;and thus
 * this instance&mdash;outlives them, but it is intentionally <em>not</em>
 * persisted across application restarts.  Only one in-progress game is
 * kept; saving another replaces it.</p>
 *
 * @author Claude Opus 4.8
 */
public final class GameState {

    private static final String LOG_TAG = "GameState";

    private static GameState instance;

    /** The goal being solved, or {@code null} for a free-play sketch. */
    @Nullable
    private TangramPuzzle goal;

    /**
     * A snapshot of the pieces the player had placed, or {@code null} if
     * there is no saved game.
     */
    @Nullable
    private TangramPuzzle playField;

    /** The saved user zoom multiplier (relative to fit-to-view). */
    private float zoom = 1f;

    /** The saved pan offsets, in view pixels. */
    private float panX = 0f;
    private float panY = 0f;

    private GameState() {
    }

    /**
     * @return the single {@code GameState} instance.
     */
    public static GameState getInstance() {
        if (instance == null)
            instance = new GameState();
        return instance;
    }

    /**
     * Save an in-progress game so it can be resumed later.  Independent
     * copies of both puzzles are stored, so later edits to the live game do
     * not affect the saved snapshot.
     *
     * @param goal the goal being solved, or {@code null} for free play
     * @param playField the pieces placed so far
     * @param zoom the current user zoom multiplier
     * @param panX the current horizontal pan offset, in view pixels
     * @param panY the current vertical pan offset, in view pixels
     */
    public void saveInProgress(@Nullable TangramPuzzle goal,
                               @NonNull TangramPuzzle playField,
                               float zoom, float panX, float panY) {
        this.goal = (goal == null) ? null : goal.clone();
        this.playField = playField.clone();
        this.zoom = zoom;
        this.panX = panX;
        this.panY = panY;
        Log.d(LOG_TAG, String.format(Locale.US,
                "Saved game: %s, %d pieces on the field",
                (goal == null) ? "free play" : ("goal=" + goal.getName()),
                playField.getPieceCount()));
    }

    /** @return the saved user zoom multiplier. */
    public float getZoom() {
        return zoom;
    }

    /** @return the saved horizontal pan offset, in view pixels. */
    public float getPanX() {
        return panX;
    }

    /** @return the saved vertical pan offset, in view pixels. */
    public float getPanY() {
        return panY;
    }

    /**
     * @return {@code true} if a resumable in-progress game is saved.
     */
    public boolean hasInProgressGame() {
        return playField != null;
    }

    /**
     * @return the saved goal, or {@code null} for a free-play game or when
     * no game is saved.
     */
    @Nullable
    public TangramPuzzle getGoal() {
        return goal;
    }

    /**
     * @return the saved play field, or {@code null} if no game is saved.
     */
    @Nullable
    public TangramPuzzle getPlayField() {
        return playField;
    }

    /**
     * Discard any saved in-progress game.
     */
    public void clear() {
        goal = null;
        playField = null;
    }
}