/*
 * This class generated by Claude Code (Opus 4.8)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.xmission.trevin.android.tangram.data;

import androidx.annotation.NonNull;

/**
 * A straight edge (line segment) between two {@link TPoint}s, with the
 * Euclidean geometry helpers the piece-snapping logic needs: angle,
 * parallelism, projection, point-to-segment distance, and overlap.
 *
 * <p>This is the geometry foundation for snapping.  Detection is done in
 * ordinary Cartesian (float/double) space via {@link TPoint#getX()}/
 * {@link TPoint#getY()}; the exact <i>a</i>&nbsp;+&nbsp;<i>b</i>&#8730;2&#773;
 * form is preserved only where it is naturally exact (e.g.
 * {@link #midpoint()}).  A {@code TEdge} holds references to its endpoints;
 * callers building edges from {@link TangramPiece#getVertices()} should use
 * them before the piece&rsquo;s transform changes.</p>
 *
 * @author Claude Opus 4.8
 */
public class TEdge {

    private final TPoint start;
    private final TPoint end;
    private final TPoint midpoint;

    /**
     * Construct an edge from {@code start} to {@code end}.
     */
    public TEdge(@NonNull TPoint start, @NonNull TPoint end) {
        this.start = start;
        this.end = end;
        this.midpoint = new ImmutableTPoint(
                (start.getXa() + end.getXa()) / 2,
                (start.getXb() + end.getXb()) / 2,
                (start.getYa() + end.getYa()) / 2,
                (start.getYb() + end.getYb()) / 2);
    }

    /** @return the starting endpoint of this edge. */
    @NonNull
    public TPoint getStart() {
        return start;
    }

    /** @return the ending endpoint of this edge. */
    @NonNull
    public TPoint getEnd() {
        return end;
    }

    /** @return the change in X from {@link #start} to {@link #end}. */
    public double getDx() {
        return end.getX() - start.getX();
    }

    /** @return the change in Y from {@link #start} to {@link #end}. */
    public double getDy() {
        return end.getY() - start.getY();
    }

    /** @return the length of this edge. */
    public double length() {
        return Math.hypot(getDx(), getDy());
    }

    /**
     * @return the midpoint of this edge, computed exactly in
     * &#8474;[&#8730;2] by averaging the endpoint coefficients.
     */
    @NonNull
    public TPoint midpoint() {
        return midpoint;
    }

    /**
     * @return the direction of this edge, from {@link #start} to
     * {@link #end}, in degrees normalized to [0,&nbsp;360).
     */
    public double angleDegrees() {
        double angle = Math.toDegrees(Math.atan2(getDy(), getDx()));
        return (angle < 0) ? angle + 360 : angle;
    }

    /**
     * Measure how far two edges are from being parallel, treating each as
     * an undirected line (so opposite directions count as parallel).
     *
     * @param other the edge to compare against
     * @return the angle between the two lines in degrees, in [0,&nbsp;90]
     */
    public double lineAngleDifference(@NonNull TEdge other) {
        double diff = Math.abs(angleDegrees() - other.angleDegrees()) % 180.0;
        return (diff > 90.0) ? 180.0 - diff : diff;
    }

    /**
     * @param other the edge to compare against
     * @param toleranceDegrees the maximum line-angle difference to allow
     * @return whether the two edges are parallel within the tolerance
     */
    public boolean isNearlyParallel(
            @NonNull TEdge other, double toleranceDegrees) {
        return lineAngleDifference(other) < toleranceDegrees;
    }

    /**
     * The position of {@code p}&rsquo;s perpendicular projection along the
     * infinite line through this edge, as a fraction where 0 is
     * {@link #start} and 1 is {@link #end}.  Values outside [0,&nbsp;1]
     * project beyond the segment.  A degenerate (zero-length) edge yields 0.
     *
     * @param p the point to project
     * @return the projection fraction
     */
    public double projectionFraction(@NonNull TPoint p) {
        double dx = getDx(), dy = getDy();
        double lengthSquared = dx * dx + dy * dy;
        if (lengthSquared == 0)
            return 0;
        return ((p.getX() - start.getX()) * dx
                + (p.getY() - start.getY()) * dy) / lengthSquared;
    }

    /**
     * @param fraction a position along the edge (0 = start, 1 = end); may
     * lie outside [0,&nbsp;1] to extend the line
     * @return the point at that fraction of the edge
     */
    @NonNull
    public TPoint pointAtFraction(double fraction) {
        return new ImmutableTPoint(
                (float) (start.getX() + fraction * getDx()), 0f,
                (float) (start.getY() + fraction * getDy()), 0f);
    }

    /**
     * @param p the point to find the nearest edge point to
     * @return the closest point <em>on this segment</em> to {@code p}
     * (an endpoint if {@code p} projects beyond the segment)
     */
    @NonNull
    public TPoint nearestPointTo(@NonNull TPoint p) {
        double fraction = Math.max(0, Math.min(1, projectionFraction(p)));
        return pointAtFraction(fraction);
    }

    /**
     * @param p the point to measure to
     * @return the distance from {@code p} to the nearest point on this
     * segment
     */
    public double distanceToPoint(@NonNull TPoint p) {
        return nearestPointTo(p).distanceTo(p);
    }

    /**
     * @param p the point to measure to
     * @return the perpendicular distance from {@code p} to the infinite
     * line through this edge (ignoring the segment&rsquo;s endpoints)
     */
    public double perpendicularDistanceToLine(@NonNull TPoint p) {
        double length = length();
        if (length == 0)
            return start.distanceTo(p);
        double cross = getDx() * (p.getY() - start.getY())
                - getDy() * (p.getX() - start.getX());
        return Math.abs(cross) / length;
    }

    /**
     * Length over which {@code other} overlaps this edge when both are
     * projected onto this edge&rsquo;s direction.  A positive result means
     * the edges overlap along their shared direction (the usual
     * edge-to-edge contact); a value at or below zero means they meet only
     * end-to-end or with a gap (treated as a vertex contact by the snapping
     * rules).  This considers only the along-direction extent, not the
     * perpendicular separation&mdash;combine with
     * {@link #perpendicularDistanceToLine(TPoint)} and
     * {@link #isNearlyParallel(TEdge, double)} to decide edge contact.
     *
     * @param other the other edge
     * @return the signed overlap length
     */
    public double overlapLength(@NonNull TEdge other) {
        double t1 = projectionFraction(other.start);
        double t2 = projectionFraction(other.end);
        double low = Math.min(t1, t2);
        double high = Math.max(t1, t2);
        double overlapFraction =
                Math.min(1, high) - Math.max(0, low);
        return overlapFraction * length();
    }

    @NonNull
    @Override
    public String toString() {
        return "TEdge[" + start + " -> " + end + "]";
    }
}