/*
 * This class generated by Claude Code (Opus 4.8)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.xmission.trevin.android.tangram.util;

import android.os.Handler;
import android.os.Looper;

import androidx.annotation.NonNull;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

/**
 * A small shared executor for off-main-thread file work (loading and
 * saving puzzles through the Storage Access Framework) with a helper for
 * posting results back to the main thread.
 *
 * <p>A single worker thread serializes SAF access, which avoids concurrent
 * read/write races against the same document provider and keeps the
 * ordering of load/save operations predictable.</p>
 *
 * @author Claude Opus 4.8
 */
public final class BackgroundExecutor {

    private static final ExecutorService IO =
            Executors.newSingleThreadExecutor(runnable -> {
                Thread thread = new Thread(runnable, "tangram-io");
                thread.setPriority(Thread.NORM_PRIORITY - 1);
                return thread;
            });

    private static final Handler MAIN = new Handler(Looper.getMainLooper());

    private BackgroundExecutor() {
    }

    /**
     * Run a task on the shared background I/O thread.
     *
     * @param task the work to run off the main thread
     */
    public static void runInBackground(@NonNull Runnable task) {
        IO.execute(task);
    }

    /**
     * Post a task to the main (UI) thread.
     *
     * @param task the work to run on the main thread
     */
    public static void runOnMain(@NonNull Runnable task) {
        MAIN.post(task);
    }
}