/*
 * This class generated by Claude Code (Opus 4.8)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.xmission.trevin.android.tangram.util;

import androidx.annotation.NonNull;

import java.util.Locale;

/**
 * Naming rules for user-saved puzzles, shared by the save dialog (the ID
 * hint), {@code PlayActivity} (the actual save + file name), and
 * {@code PuzzleListAdapter} (collection display), so all three stay in sync.
 *
 * <p>A <b>collection</b> becomes part of the save file name, so it is made
 * filename-safe: spaces become underscores (and, for display, underscores
 * become spaces again).  A puzzle <b>ID</b> follows the XML
 * <a href="https://www.w3.org/TR/xml-names/#NT-NCName">NCName</a> rules&mdash;
 * it may contain letters, digits, {@code '-'}, {@code '.'}, and {@code '_'},
 * and must begin with a letter or underscore.</p>
 *
 * @author Claude Opus 4.8
 */
public final class PuzzleNaming {

    /** Characters disallowed anywhere in a collection name or ID. */
    private static final String DISALLOWED = "[^-.\\p{N}_\\p{L}]";

    /** Non-alphanumeric characters (for trimming the name part of an ID). */
    private static final String NON_ALNUM = "[^\\p{L}\\p{N}]";

    private PuzzleNaming() {
    }

    /**
     * Normalize a collection name into a filename-safe form: trim leading and
     * trailing whitespace, {@code '.'}, and {@code '-'} (a leading underscore
     * is kept, being a valid start), turn internal whitespace runs into single
     * underscores, and drop any remaining disallowed characters.
     *
     * @param raw the collection name as entered
     * @return the normalized collection, possibly empty (the caller supplies a
     * default in that case)
     */
    @NonNull
    public static String normalizeCollection(String raw) {
        if (raw == null)
            return "";
        return raw.replaceFirst("^[\\s.-]+", "")
                .replaceFirst("[\\s.-]+$", "")
                .replaceAll("\\s+", "_")
                .replaceAll(DISALLOWED, "");
    }

    /**
     * Convert a stored (filename-safe) collection name back to a display form
     * by turning underscores into spaces.
     *
     * @param stored the stored collection name
     * @return the collection name for display
     */
    @NonNull
    public static String displayCollection(String stored) {
        return (stored == null) ? "" : stored.replace('_', ' ');
    }

    /**
     * Normalize a puzzle name into the name portion of a default ID:
     * lower-cased, internal whitespace turned into single dashes, disallowed
     * characters dropped, and leading/trailing non-alphanumerics trimmed.
     *
     * @param rawName the puzzle name as entered
     * @return the name portion for a default ID, possibly empty
     */
    @NonNull
    public static String normalizeNameForId(String rawName) {
        if (rawName == null)
            return "";
        return rawName.strip().toLowerCase(Locale.ROOT)
                .replaceAll("\\s+", "-")
                .replaceAll(DISALLOWED, "")
                .replaceFirst("^" + NON_ALNUM + "+", "")
                .replaceFirst(NON_ALNUM + "+$", "");
    }

    /**
     * Build the default puzzle ID from a normalized collection and a raw
     * puzzle name: {@code collection + "-" + normalizedName}, forced to start
     * with a letter or underscore.
     *
     * @param normalizedCollection a non-empty normalized collection name
     * @param rawName the puzzle name as entered
     * @return the default ID (a valid NCName)
     */
    @NonNull
    public static String defaultId(@NonNull String normalizedCollection,
                                   String rawName) {
        return ensureNcNameStart(
                normalizedCollection + "-" + normalizeNameForId(rawName));
    }

    /**
     * Sanitize an explicitly-entered ID: drop disallowed characters and force
     * a valid NCName start, but otherwise leave it untouched (mixed case is
     * allowed, and no collection/name substitutions are made).
     *
     * @param rawId the ID as entered
     * @return the sanitized ID, or an empty string if nothing usable remains
     */
    @NonNull
    public static String sanitizeId(String rawId) {
        if (rawId == null)
            return "";
        return ensureNcNameStart(rawId.strip().replaceAll(DISALLOWED, ""));
    }

    /**
     * Ensure an ID begins with a letter or underscore (prefixing an
     * underscore if it starts with a digit, {@code '-'}, or {@code '.'}), as
     * NCName requires.  An empty ID is returned unchanged.
     *
     * @param id the ID to check
     * @return an ID that starts with a letter or underscore
     */
    @NonNull
    public static String ensureNcNameStart(@NonNull String id) {
        if (id.isEmpty())
            return id;
        int first = id.codePointAt(0);
        return (Character.isLetter(first) || first == '_') ? id : "_" + id;
    }
}