/*
 * This class generated by Claude Code (Opus 4.8)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.xmission.trevin.android.tangram.ui;

import android.os.Bundle;
import android.util.Log;
import android.widget.ImageButton;
import android.widget.ListView;

import androidx.annotation.Nullable;
import androidx.appcompat.view.ContextThemeWrapper;

import com.xmission.trevin.android.tangram.R;
import com.xmission.trevin.android.tangram.data.TangramPuzzle;

import java.util.Locale;

/**
 * Displays the puzzle library as a scrollable list; tapping a puzzle opens
 * it as a goal to solve in {@link PlayActivity}.
 *
 * <p>Unlike the (deprecated) {@code ListActivity}, this is an ordinary
 * activity hosting a {@link ListView} wired to a {@link PuzzleListAdapter}.
 * The activity chrome (title and back button) uses the default
 * piece-coloring theme like the rest of the app; only the puzzle
 * silhouettes in the list follow the <em>hint level</em> preference (like
 * the goal view in {@link PlayActivity}), via a hint-themed context given
 * to the adapter.</p>
 *
 * @author Claude Opus 4.8
 */
public class LibraryActivity extends TangramActivity {

    private static final String LOG_TAG = "LibraryActivity";

    private PuzzleListAdapter adapter;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Log.d(LOG_TAG, String.format(Locale.US, "onCreate(%s)",
                savedInstanceState == null ? "" : "saved state"));
        setContentView(R.layout.activity_library);
        WindowInsetsUtil.applySafeAreaPadding(this);

        // The activity chrome (title, back button) uses the default
        // piece-coloring theme; only the puzzle previews follow the hint
        // level, so give the adapter a hint-themed context to inflate rows.
        adapter = new PuzzleListAdapter(
                new ContextThemeWrapper(this, resolveHintThemeResource()));
        ListView list = findViewById(R.id.LibraryPuzzleList);
        list.setEmptyView(findViewById(R.id.LibraryEmpty));
        list.setAdapter(adapter);
        list.setOnItemClickListener((parent, view, position, id) -> {
            TangramPuzzle puzzle = adapter.getItem(position);
            if (puzzle == null)
                return;
            Log.d(LOG_TAG, "Selected puzzle: " + puzzle.getName());
            startActivity(PlayActivity.createIntent(this, puzzle));
        });

        ImageButton backButton = findViewById(R.id.LibraryButtonBack);
        backButton.setOnClickListener(v -> finish());
    }

    @Override
    protected void onResume() {
        super.onResume();
        // User puzzles may finish loading in the background after this screen
        // first appears, so refresh to pick up any that have arrived.
        adapter.notifyDataSetChanged();
    }
}