/*
 * This class generated by Claude Code (Opus 4.8)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.xmission.trevin.android.tangram.ui;

import android.content.ClipData;
import android.content.Context;
import android.content.res.TypedArray;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Path;
import android.graphics.Point;
import android.graphics.drawable.Drawable;
import android.os.Build;
import android.os.Parcel;
import android.os.Parcelable;
import android.util.AttributeSet;
import android.util.SparseArray;
import android.util.TypedValue;
import android.view.LayoutInflater;
import android.view.MotionEvent;
import android.view.View;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.StringRes;
import androidx.appcompat.content.res.AppCompatResources;
import androidx.core.content.ContextCompat;

import com.xmission.trevin.android.tangram.R;
import com.xmission.trevin.android.tangram.data.*;

/**
 * A single slot in the piece tray: it shows an image of one type of
 * {@link TangramPiece} (in the current theme colors) with a badge for
 * how many of that type are still available to add to the play field,
 * and it starts a drag-and-drop gesture so the player can drag a new
 * piece onto the {@link PlayTableView}.
 *
 * <p>The kind of piece and its starting count are declared in the layout
 * via the {@code app:pieceType} and {@code app:pieceCount} attributes.
 * Each slot holds a {@link PieceFactory} rather than a single piece so
 * that every drag creates a fresh, independent piece.</p>
 *
 * @author Claude Opus 4.8
 */
public class PieceTrayItemView extends FrameLayout {

    /** Creates new instances of one kind of piece for this slot. */
    public interface PieceFactory {
        @NonNull TangramPiece create();
    }

    /** Supplies the play field&rsquo;s current scale, in px per puzzle unit. */
    public interface UnitScaleProvider {
        float getUnitScale();
    }

    /**
     * The kinds of piece a tray slot can dispense.  The order MUST match
     * the {@code pieceType} enum in {@code attrs.xml}, since the attribute
     * value indexes into {@link #values()}.
     */
    public enum PieceType {
        SMALL_TRIANGLE(TangramSmallTriangle.class,
                TangramSmallTriangle::new, R.string.PieceNameSmallTriangle),
        SQUARE(TangramSquare.class,
                TangramSquare::new, R.string.PieceNameSquare),
        PARALLELOGRAM(TangramParallelogram.class,
                TangramParallelogram::new, R.string.PieceNameParallelogram),
        MEDIUM_TRIANGLE(TangramMediumTriangle.class,
                TangramMediumTriangle::new, R.string.PieceNameMediumTriangle),
        LARGE_TRIANGLE(TangramLargeTriangle.class,
                TangramLargeTriangle::new, R.string.PieceNameLargeTriangle);

        final Class<? extends TangramPiece> pieceClass;
        final PieceFactory factory;
        @StringRes final int nameRes;

        PieceType(@NonNull Class<? extends TangramPiece> pieceClass,
                  @NonNull PieceFactory factory, @StringRes int nameRes) {
            this.pieceClass = pieceClass;
            this.factory = factory;
            this.nameRes = nameRes;
        }

        /** @return whether {@code piece} is of this kind. */
        boolean matches(@NonNull TangramPiece piece) {
            return pieceClass.isInstance(piece);
        }
    }

    private ImageView pieceImage;
    private TextView countText;

    /** The kind of piece this slot dispenses, or {@code null} if unset. */
    @Nullable
    private PieceType pieceType;

    /** Factory for the kind of piece this slot dispenses. */
    @Nullable
    private PieceFactory factory;

    /** Human-readable name of the piece, for content descriptions. */
    @Nullable
    private CharSequence pieceName;

    /** How many pieces of this kind remain available to add. */
    private int count;

    /**
     * Supplies the play field&rsquo;s scale so the drag shadow can match
     * the size the piece will have once dropped.  May be {@code null}, in
     * which case the drag falls back to a tray-sized shadow.
     */
    @Nullable
    private UnitScaleProvider unitScaleProvider;

    public PieceTrayItemView(@NonNull Context context) {
        super(context);
        init(context);
    }

    public PieceTrayItemView(@NonNull Context context, @Nullable AttributeSet attrs) {
        super(context, attrs);
        init(context);
        try (TypedArray a = context.obtainStyledAttributes(
                        attrs, R.styleable.PieceTrayItemView)) {
            int typeIndex = a.getInt(R.styleable.PieceTrayItemView_pieceType, 0);
            int initialCount = a.getInt(R.styleable.PieceTrayItemView_pieceCount, 0);
            PieceType[] types = PieceType.values();
            if (typeIndex < 0 || typeIndex >= types.length)
                typeIndex = 0;
            setPieceType(types[typeIndex], initialCount);
        }
    }

    private void init(@NonNull Context context) {
        LayoutInflater.from(context).inflate(
                R.layout.view_piece_tray_item, this, true);
        pieceImage = findViewById(R.id.piece_image);
        countText = findViewById(R.id.piece_count);
        // The whole slot is the accessibility target and click target.
        setFocusable(true);
        setClickable(true);
    }

    /**
     * @return the natural (drawable intrinsic) width of the piece image in
     * pixels, or 0 if unknown.  {@link PieceTrayLayout} uses this and
     * {@link #getNaturalHeight()} to size every slot at one shared scale.
     */
    public int getNaturalWidth() {
        Drawable image = pieceImage.getDrawable();
        return (image != null) ? image.getIntrinsicWidth() : 0;
    }

    /**
     * @return the natural (drawable intrinsic) height of the piece image in
     * pixels, or 0 if unknown.
     */
    public int getNaturalHeight() {
        Drawable image = pieceImage.getDrawable();
        return (image != null) ? image.getIntrinsicHeight() : 0;
    }

    /**
     * Configure this slot for a kind of piece and its starting count.
     *
     * @param type  the kind of piece this slot dispenses
     * @param count the initial number available to add
     */
    public void setPieceType(@NonNull PieceType type, int count) {
        this.pieceType = type;
        this.factory = type.factory;
        this.pieceName = getResources().getText(type.nameRes);
        // A sample instance tells us which drawable to display.  The
        // drawable references the theme's tangram*Color attributes, so
        // AppCompatResources renders it in the current mode's colors.
        TangramPiece sample = type.factory.create();
        pieceImage.setImageDrawable(AppCompatResources.getDrawable(
                getContext(), sample.getDrawableId()));
        setCount(count);
    }

    /** @return how many pieces of this kind remain available to add. */
    public int getCount() {
        return count;
    }

    /** Set the available count, updating the badge and enabled state. */
    public void setCount(int count) {
        this.count = Math.max(0, count);
        countText.setText(getResources().getString(
                R.string.piece_count_format, this.count));
        // Hide the count if there is less than 2 pieces available
        countText.setVisibility((this.count < 2) ? GONE : VISIBLE);
        // Dim and disable the slot when the player has used all of them.
        boolean available = this.count > 0;
        setEnabled(available);
        setAlpha(available ? 1f : 0.35f);
        setContentDescription(getResources().getString(
                R.string.piece_tray_item_description,
                pieceName == null ? "" : pieceName, this.count));
    }

    /** Reduce the available count by one (never below zero). */
    public void decrement() {
        setCount(count - 1);
    }

    /**
     * @return whether this slot dispenses the same kind of piece as the
     * given one, i.e. a piece returned from the field belongs here
     */
    public boolean accepts(@NonNull TangramPiece piece) {
        return pieceType != null && pieceType.matches(piece);
    }

    /**
     * Provide the play field&rsquo;s scale so a dragged piece can be shown
     * at its eventual on-field size.
     *
     * @param provider the scale source, or {@code null} to clear it
     */
    public void setUnitScaleProvider(@Nullable UnitScaleProvider provider) {
        unitScaleProvider = provider;
    }

    /** Create a fresh piece of this slot&rsquo;s kind. */
    @NonNull
    public TangramPiece createPiece() {
        if (factory == null)
            throw new IllegalStateException("Tray slot was not configured");
        return factory.create();
    }

    @Override
    public boolean onTouchEvent(@NonNull MotionEvent event) {
        // Touching a stocked slot starts dragging a new piece out of it.
        // The actual piece is created and placed when it is dropped on the
        // PlayTableView (see PlayActivity's OnDragListener).
        if (event.getActionMasked() == MotionEvent.ACTION_DOWN
                && count > 0 && factory != null) {
            startPieceDrag();
            return true;
        }
        return super.onTouchEvent(event);
    }

    /** Begin a drag-and-drop gesture carrying this slot as its state. */
    private void startPieceDrag() {
        ClipData clip = ClipData.newPlainText(
                pieceName == null ? "" : pieceName, "");
        View.DragShadowBuilder shadow = buildDragShadow();
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N)
            startDragAndDrop(clip, shadow, this, 0);
        else
            startDrag(clip, shadow, this, 0);
    }

    /**
     * Build the drag shadow.  When the play field&rsquo;s scale is known,
     * the shadow is the piece&rsquo;s polygon drawn at that scale&mdash;the
     * same geometry and size {@link PlayTableView} will give it&mdash;so it
     * doesn&rsquo;t change size when dropped.  Otherwise it falls back to
     * the tray-sized image.
     */
    @NonNull
    private View.DragShadowBuilder buildDragShadow() {
        float unitScale = (unitScaleProvider != null)
                ? unitScaleProvider.getUnitScale() : 0f;
        if (factory == null || unitScale <= 0f)
            return new View.DragShadowBuilder(pieceImage);

        // A fresh piece is at its default orientation with its centroid at
        // the origin, so its vertices are centred on (0, 0).
        TangramPiece piece = factory.create();
        TPoint[] vertices = piece.getVertices();
        float minX = Float.MAX_VALUE, minY = Float.MAX_VALUE;
        float maxX = -Float.MAX_VALUE, maxY = -Float.MAX_VALUE;
        for (TPoint v : vertices) {
            minX = Math.min(minX, v.getX());
            maxX = Math.max(maxX, v.getX());
            minY = Math.min(minY, v.getY());
            maxY = Math.max(maxY, v.getY());
        }
        Path path = new Path();
        for (int i = 0; i < vertices.length; i++) {
            float px = (vertices[i].getX() - minX) * unitScale;
            float py = (vertices[i].getY() - minY) * unitScale;
            if (i == 0)
                path.moveTo(px, py);
            else
                path.lineTo(px, py);
        }
        path.close();

        int width = Math.max(1, Math.round((maxX - minX) * unitScale));
        int height = Math.max(1, Math.round((maxY - minY) * unitScale));
        // The centroid is the vertex origin, so its offset within the shadow
        // is (-min * scale).  Anchoring the finger there means dropping the
        // piece leaves its centroid under the finger (matching
        // PlayTableView.addPieceAtViewLocation).
        int touchX = Math.round(-minX * unitScale);
        int touchY = Math.round(-minY * unitScale);
        int color = resolveThemeColor(piece.getColorAttr());
        return new PiecePolygonShadow(path, width, height, touchX, touchY, color);
    }

    /** Resolve a theme color attribute to an ARGB value. */
    private int resolveThemeColor(int attrRes) {
        TypedValue tv = new TypedValue();
        if (getContext().getTheme().resolveAttribute(attrRes, tv, true)) {
            if (tv.resourceId != 0)
                return ContextCompat.getColor(getContext(), tv.resourceId);
            return tv.data;
        }
        return Color.GRAY;
    }

    @Override
    public boolean performClick() {
        super.performClick();
        return true;
    }

    /**
     * A drag shadow that paints the piece as a filled polygon at a fixed
     * pixel size&mdash;used to preview a tray piece at its eventual
     * on-field size while it is being dragged.
     */
    private static class PiecePolygonShadow extends View.DragShadowBuilder {

        private final Path path;
        private final int width, height, touchX, touchY;
        private final Paint paint;

        PiecePolygonShadow(@NonNull Path path, int width, int height,
                           int touchX, int touchY, int color) {
            this.path = path;
            this.width = width;
            this.height = height;
            this.touchX = touchX;
            this.touchY = touchY;
            paint = new Paint(Paint.ANTI_ALIAS_FLAG);
            paint.setStyle(Paint.Style.FILL);
            paint.setColor(color);
        }

        @Override
        public void onProvideShadowMetrics(@NonNull Point outShadowSize,
                                           @NonNull Point outShadowTouchPoint) {
            outShadowSize.set(width, height);
            outShadowTouchPoint.set(touchX, touchY);
        }

        @Override
        public void onDrawShadow(@NonNull Canvas canvas) {
            canvas.drawPath(path, paint);
        }
    }

    /*
     * The inner image and count label are the same layout inflated into
     * every slot, so they share view ids.  Save/restore only this slot's
     * own state (its count) to keep those duplicate ids from colliding in
     * the id-keyed hierarchy state.
     */

    @Override
    protected void dispatchSaveInstanceState(@NonNull SparseArray<Parcelable> container) {
        dispatchFreezeSelfOnly(container);
    }

    @Override
    protected void dispatchRestoreInstanceState(@NonNull SparseArray<Parcelable> container) {
        dispatchThawSelfOnly(container);
    }

    @Override
    protected Parcelable onSaveInstanceState() {
        SavedState state = new SavedState(super.onSaveInstanceState());
        state.count = count;
        return state;
    }

    @Override
    protected void onRestoreInstanceState(Parcelable state) {
        if (!(state instanceof SavedState ss)) {
            super.onRestoreInstanceState(state);
            return;
        }
        super.onRestoreInstanceState(ss.getSuperState());
        setCount(ss.count);
    }

    /** Saved state for a tray slot: how many pieces remain available. */
    private static class SavedState extends BaseSavedState {

        int count;

        SavedState(Parcelable superState) {
            super(superState);
        }

        SavedState(Parcel in) {
            super(in);
            count = in.readInt();
        }

        @Override
        public void writeToParcel(@NonNull Parcel out, int flags) {
            super.writeToParcel(out, flags);
            out.writeInt(count);
        }

        public static final Parcelable.Creator<SavedState> CREATOR =
                new Parcelable.Creator<>() {
                    @Override
                    public SavedState createFromParcel(Parcel in) {
                        return new SavedState(in);
                    }

                    @Override
                    public SavedState[] newArray(int size) {
                        return new SavedState[size];
                    }
                };
    }
}
