/*
 * This class generated by Claude Code (Opus 4.8)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.xmission.trevin.android.tangram.ui;

import android.app.AlertDialog;
import android.content.Context;
import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.util.Log;
import android.view.DragEvent;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.ImageButton;
import android.widget.LinearLayout;
import android.widget.Toast;

import androidx.activity.OnBackPressedCallback;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.view.ContextThemeWrapper;
import androidx.core.content.IntentCompat;
import androidx.documentfile.provider.DocumentFile;

import com.xmission.trevin.android.tangram.R;
import com.xmission.trevin.android.tangram.data.*;
import com.xmission.trevin.android.tangram.util.BackgroundExecutor;
import com.xmission.trevin.android.tangram.util.FileUtils;
import com.xmission.trevin.android.tangram.util.PuzzleNaming;

import java.io.File;
import java.util.Locale;

/**
 * The screen where the player actually assembles a Tangram.  It hosts a
 * {@link PlayTableView} for the play surface and a tray of
 * {@link PieceTrayItemView}s&mdash;one per kind of piece&mdash;from which
 * pieces can be dragged onto the surface.
 *
 * <p>This is not the launcher activity; it is started from the home
 * screen either for a chosen goal puzzle (via {@link #createIntent}) or
 * for free-play / sketch mode (with a {@code null} puzzle).</p>
 *
 * @author Claude Opus 4.8
 */
public class PlayActivity extends TangramActivity
        implements SavePuzzleDialogFragment.OnSavePuzzleListener {

    private static final String LOG_TAG = "PlayActivity";

    /**
     * Intent extra carrying the goal puzzle.  Absent for free-play mode.
     */
    public static final String EXTRA_PUZZLE_GOAL =
            "com.xmission.trevin.android.tangram.PUZZLE_GOAL";

    /**
     * Intent extra carrying the placed pieces of a game being resumed.
     * Present only when launched via {@link #createResumeIntent}.
     */
    public static final String EXTRA_RESUME_PLAYFIELD =
            "com.xmission.trevin.android.tangram.RESUME_PLAYFIELD";

    /**
     * Intent extras carrying the viewport (zoom and pan) of a game being
     * resumed.  Present only when launched via {@link #createResumeIntent}.
     */
    public static final String EXTRA_RESUME_ZOOM =
            "com.xmission.trevin.android.tangram.RESUME_ZOOM";
    public static final String EXTRA_RESUME_PAN_X =
            "com.xmission.trevin.android.tangram.RESUME_PAN_X";
    public static final String EXTRA_RESUME_PAN_Y =
            "com.xmission.trevin.android.tangram.RESUME_PAN_Y";

    private TangramPreferences prefs;

    private PuzzleLibrary library = null;

    private PlayTableView playTableView;

    private ViewGroup saveButtonFrame;

    /** Reference to the puzzle name toast if we show one, otherwise null */
    private Toast puzzleToast = null;

    /**
     * This will be set when the user has solved the puzzle goal if
     * there is one, or after saving a puzzle in free-play mode.
     */
    private boolean isFinished = false;

    /**
     * The goal region, computed once on the first solution check (the goal
     * is static) and reused; the play field&rsquo;s region is recomputed
     * each check.  Null in free play or until the first check.
     */
    private TPolygon goalPolygon;

    /**
     * The values last entered in the save dialog this session, remembered so
     * the dialog can pre-fill them when saving a series of related puzzles.
     */
    private String lastSaveCollection = "";
    private String lastSaveName = "";
    private String lastSaveId = "";

    /**
     * Build an intent to start this activity.
     *
     * @param context the launching context
     * @param goal    the goal puzzle to solve, or {@code null} for free play
     * @return the intent to hand to {@code startActivity}
     */
    @NonNull
    public static Intent createIntent(
            @NonNull Context context, @Nullable TangramPuzzle goal) {
        Intent intent = new Intent(context, PlayActivity.class);
        if (goal != null)
            intent.putExtra(EXTRA_PUZZLE_GOAL, goal);
        return intent;
    }

    /**
     * Build an intent to resume the game saved in {@link GameState},
     * carrying its goal (if any) and placed pieces, and consume that saved
     * game.  Call only when {@link GameState#hasInProgressGame()} is true.
     *
     * @param context the launching context
     * @return the intent to hand to {@code startActivity}
     */
    @NonNull
    public static Intent createResumeIntent(@NonNull Context context) {
        GameState state = GameState.getInstance();
        Intent intent = new Intent(context, PlayActivity.class);
        TangramPuzzle goal = state.getGoal();
        if (goal != null)
            intent.putExtra(EXTRA_PUZZLE_GOAL, goal);
        TangramPuzzle playField = state.getPlayField();
        if (playField != null)
            intent.putExtra(EXTRA_RESUME_PLAYFIELD, playField);
        intent.putExtra(EXTRA_RESUME_ZOOM, state.getZoom());
        intent.putExtra(EXTRA_RESUME_PAN_X, state.getPanX());
        intent.putExtra(EXTRA_RESUME_PAN_Y, state.getPanY());
        // The game is now live in the launched activity; free the slot so
        // the menu stops offering it (a fresh snapshot is saved on exit if
        // the player leaves it unfinished again).
        state.clear();
        return intent;
    }

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        // TangramActivity applies the hint-level theme (piece colors) before
        // the content view is inflated.
        super.onCreate(savedInstanceState);
        Log.d(LOG_TAG, String.format(Locale.US,
                "onCreate(%s)", savedInstanceState == null ? "" : "saved state"));
        setContentView(R.layout.activity_play);
        WindowInsetsUtil.applySafeAreaPadding(this);

        prefs = TangramPreferences.getInstance(this);

        playTableView = findViewById(R.id.play_table);
        Intent intent = getIntent();
        TangramPuzzle goal = IntentCompat.getParcelableExtra(
                intent, EXTRA_PUZZLE_GOAL, TangramPuzzle.class);
        playTableView.setSolution(goal);
        setUpDropTarget();
        setUpOverlayControls(goal);
        configureTraySlots();

        // Restore a game being resumed.  Only on a fresh create: on a
        // configuration change (savedInstanceState != null) the view
        // hierarchy restores the placed pieces and tray counts itself.
        boolean resuming = false;
        if (savedInstanceState == null) {
            TangramPuzzle resumeField = IntentCompat.getParcelableExtra(
                    intent, EXTRA_RESUME_PLAYFIELD, TangramPuzzle.class);
            if (resumeField != null) {
                restoreInProgressPieces(resumeField);
                // Restore the zoom and pan the game was saved at.
                playTableView.setViewport(
                        intent.getFloatExtra(EXTRA_RESUME_ZOOM, 1f),
                        intent.getFloatExtra(EXTRA_RESUME_PAN_X, 0f),
                        intent.getFloatExtra(EXTRA_RESUME_PAN_Y, 0f));
                resuming = true;
            }
        }

        // If we have a goal, show a temporary toast giving
        // the name of the puzzle.  This is chiefly used during
        // development to identify malformed puzzles.
        if (goal != null && !resuming) {
            if (!goal.getName().isEmpty()) {
                Log.d(LOG_TAG, "Goal: " + goal.getName());
                puzzleToast = Toast.makeText(this,
                                goal.getName(), Toast.LENGTH_LONG);
                puzzleToast.show();
            } else {
                Log.d(LOG_TAG, "Unnamed goal provided:" + goal);
            }
        }
    }

    /**
     * Give each tray slot the play field&rsquo;s scale so a dragged piece
     * previews at the size it will have once dropped.
     */
    private void configureTraySlots() {
        ViewGroup tray = findViewById(R.id.piece_tray);
        for (int i = 0; i < tray.getChildCount(); i++) {
            View child = tray.getChildAt(i);
            if (child instanceof PieceTrayItemView)
                ((PieceTrayItemView) child).setUnitScaleProvider(
                        playTableView::getUnitScale);
        }
    }

    /**
     * Restore the placed pieces of a resumed game onto the (already
     * goal-configured) play field and remove them from the tray, as if the
     * player had dragged each one in.
     *
     * @param savedField the saved snapshot of placed pieces
     */
    private void restoreInProgressPieces(@NonNull TangramPuzzle savedField) {
        Log.d(LOG_TAG, String.format(Locale.US,
                "Restoring %d pieces from saved game",
                savedField.getPieceCount()));
        playTableView.getPuzzle().addPieces(savedField.getPieces());
        ViewGroup tray = findViewById(R.id.piece_tray);
        for (TangramPiece piece : savedField.getPieces()) {
            for (int i = 0; i < tray.getChildCount(); i++) {
                View child = tray.getChildAt(i);
                if (child instanceof PieceTrayItemView slot
                        && slot.accepts(piece)) {
                    slot.setCount(Math.max(0, slot.getCount() - 1));
                    break;
                }
            }
        }
        playTableView.invalidate();
    }

    /**
     * Leave the play screen, saving an unfinished game that has some pieces
     * placed so the main menu can offer to resume it.  (An empty board isn't
     * worth saving, and leaving it alone preserves any earlier saved game.)
     * Shared by the Exit hover control and the system Back button/gesture.
     */
    private void exitPlay() {
        if (puzzleToast != null)
            puzzleToast.cancel();
        if (!isFinished && (playTableView.getPuzzle().getPieceCount() > 0)) {
            Log.d(LOG_TAG, String.format(Locale.US,
                    "Saving game state %s and %s pieces placed",
                    (playTableView.getSolution() == null)
                    ? "in free play" : ("with goal " +
                            playTableView.getSolution().getName()),
                    playTableView.getPuzzle().getPieceCount()));
            GameState.getInstance().saveInProgress(
                    playTableView.getSolution(),
                    playTableView.getPuzzle(),
                    playTableView.getZoom(),
                    playTableView.getPanX(),
                    playTableView.getPanY());
        }
        finish();
    }

    /**
     * Wire up the controls that hover over the play area: the back / exit
     * button, the goal preview (shown only when solving a puzzle), and the
     * contextual flip button (shown only while a flippable piece&mdash;the
     * parallelogram&mdash;is selected).
     *
     * @param goal the goal puzzle to display if any, or {@code null}
     * for free-play mode
     */
    private void setUpOverlayControls(@Nullable TangramPuzzle goal) {
        ViewGroup backFrame = findViewById(R.id.button_back_frame);
        moveControlToCorner(R.id.button_back_frame,
                prefs.getBackButtonCorner());
        findViewById(R.id.button_back).setOnClickListener((v) -> exitPlay());
        // The system Back button (and back gesture) must exit the same way,
        // saving the in-progress game; the default dispatcher would just
        // finish() without our save logic.
        getOnBackPressedDispatcher().addCallback(this,
                new OnBackPressedCallback(true) {
                    @Override
                    public void handleOnBackPressed() {
                        exitPlay();
                    }
                });

        ViewGroup goalFrame = findViewById(R.id.goal_view_frame);
        if (prefs.getHintLevel() != prefs.getPieceColoring()) {
            // Re-theme the goal view according to the hint level.
            goalFrame.removeAllViews();
            int hintTheme = resolveHintThemeResource();
            ContextThemeWrapper themedContext =
                    new ContextThemeWrapper(this, hintTheme);
            LayoutInflater inflater = getLayoutInflater()
                    .cloneInContext(themedContext);
            View themedGoal = inflater.inflate(
                    R.layout.goal_frame, goalFrame, true);
        }
        moveControlToCorner(R.id.goal_view_frame, prefs.getGoalCorner());
        TangramPuzzleView goalView = findViewById(R.id.goal_view);
        if (goal != null) {
            goalView.setPuzzle(goal);
            goalFrame.setVisibility(View.VISIBLE);
        } else {
            goalFrame.setVisibility(View.GONE);
        }

        final ViewGroup flipFrame = findViewById(R.id.button_flip_frame);
        ImageButton flipButton = findViewById(R.id.button_flip);
        flipButton.setOnClickListener(v -> playTableView.flipSelectedPiece());
        playTableView.setOnSelectionChangedListener(selected ->
                flipFrame.setVisibility(canFlip(selected)
                        ? View.VISIBLE : View.GONE));
        // Reflect the current selection (normally none on a fresh start).
        flipFrame.setVisibility(
                canFlip(playTableView.getSelectedPiece())
                        ? View.VISIBLE : View.GONE);

        saveButtonFrame = findViewById(R.id.button_save_frame);
        moveControlToCorner(R.id.button_save_frame,
                prefs.getSaveButtonCorner());
        // We only care about saving *if* we're in free-play mode
        // and *if* the user has set up a directory for user puzzles.
        if ((goal == null) && (prefs.getUserPuzzlesDir() != null)) {
            ImageButton saveButton = findViewById(R.id.button_save);
            saveButton.setOnClickListener(v ->
                    SavePuzzleDialogFragment.newInstance(lastSaveCollection,
                                    lastSaveName, lastSaveId)
                            .show(getSupportFragmentManager(),
                                    SavePuzzleDialogFragment.TAG));
        }

        // React each time the play field becomes (or stops being) a valid
        // Tangram: reveal the "Save" button in free play, or check the
        // solution against the goal in puzzle mode.
        playTableView.setOnPuzzleValidatedListener(this::onPuzzleValidated);
    }

    /**
     * Respond to the play field becoming, or ceasing to be, a valid
     * Tangram after a piece is placed, moved, or removed.
     *
     * <p>In free-play mode a valid Tangram can be saved, so the &ldquo;Save&rdquo;
     * button is shown while the puzzle is valid (and a user-puzzle directory
     * is configured) and hidden otherwise.  In puzzle mode a valid Tangram
     * is a candidate solution to be checked against the goal.</p>
     *
     * @param valid whether the play field is currently a valid Tangram
     */
    private void onPuzzleValidated(boolean valid) {
        if (playTableView.getSolution() == null) {
            // Free play: offer to save a completed puzzle, but only if the
            // user has chosen a directory to save user puzzles into.
            saveButtonFrame.setVisibility(
                    valid && (prefs.getUserPuzzlesDir() != null)
                            ? View.VISIBLE : View.GONE);
            // Reset the finished flag if the puzzle is invalid.
            if (!valid)
                isFinished = false;
        } else if (valid) {
            // Puzzle mode: see whether this valid Tangram solves the goal.
            checkSolutionAgainstGoal();
        }
    }

    /**
     * Placeholder for checking a completed, valid Tangram against the goal
     * puzzle.
     *
     * <p>Once {@link TangramPuzzle}&nbsp;&rarr;&nbsp;{@link TPolygon}
     * conversion is implemented, this will build a {@link TPolygon} from the
     * play field and from the goal and compare them with
     * {@link TPolygon#isIdenticalTo(TPolygon)}, then react when they match
     * (e.g. congratulate the player and offer the next puzzle).</p>
     */
    private void checkSolutionAgainstGoal() {
        if (isFinished)
            return; // already solved; don't re-announce on further moves
        TangramPuzzle goal = playTableView.getSolution();
        if (goal == null)
            return;
        // The goal is static, so build its region once and reuse it; only
        // the play field's region is recomputed on each check.
        if (goalPolygon == null) {
            goalPolygon = TPolygon.fromPuzzle(goal);
            goalPolygon.build();
        }
        TPolygon current = TPolygon.fromPuzzle(playTableView.getPuzzle());
        if (!current.isIdenticalTo(goalPolygon)) {
            Log.d(LOG_TAG, "Valid Tangram formed, but it does not match the goal");
            return;
        }
        Log.d(LOG_TAG, "Puzzle solved!");
        isFinished = true;
        // Placeholder feedback.  The final "solved" experience (e.g. a
        // congratulations dialog with an option to move on to another puzzle)
        // is still to be designed.
        Toast.makeText(this, R.string.PuzzleSolved, Toast.LENGTH_LONG).show();
    }

    /**
     * Move a given hover control into the designated corner.
     *
     * @param groupId the ID of the {@link LinearLayout} containing the control
     * @param corner the corner in which to move the layout
     */
    private void moveControlToCorner(
            int groupId,
            @NonNull TangramPreferences.Corner corner) {
        LinearLayout frame = findViewById(groupId);
        FrameLayout.LayoutParams params =
                (FrameLayout.LayoutParams) frame.getLayoutParams();
        params.gravity = corner.getGravity();
        frame.setLayoutParams(params);
    }

    /** @return whether a (possibly {@code null}) piece can be flipped. */
    private static boolean canFlip(@Nullable TangramPiece piece) {
        return piece != null && piece.canFlip();
    }

    /**
     * Make the play surface accept pieces dropped from the tray, creating
     * a fresh piece there and decrementing that kind&rsquo;s tray count.
     */
    private void setUpDropTarget() {
        playTableView.setOnDragListener((view, event) -> {
            switch (event.getAction()) {
                case DragEvent.ACTION_DRAG_STARTED:
                case DragEvent.ACTION_DRAG_ENTERED:
                case DragEvent.ACTION_DRAG_LOCATION:
                case DragEvent.ACTION_DRAG_EXITED:
                case DragEvent.ACTION_DRAG_ENDED:
                    return true;

                case DragEvent.ACTION_DROP:
                    Object state = event.getLocalState();
                    if (state instanceof PieceTrayItemView slot) {
                        if (slot.getCount() > 0) {
                            TangramPiece piece = slot.createPiece();
                            playTableView.addPieceAtViewLocation(
                                    piece, event.getX(), event.getY());
                            slot.decrement();
                        }
                    }
                    return true;

                default:
                    return false;
            }
        });

        // A piece dragged off the field comes back to its tray slot.
        playTableView.setOnPieceReturnedListener(this::returnPieceToTray);
    }

    /**
     * Return a piece that was dragged off the play field to its tray slot,
     * bumping that slot&rsquo;s available count back up.
     *
     * @param piece the piece that left the field
     */
    private void returnPieceToTray(@NonNull TangramPiece piece) {
        ViewGroup tray = findViewById(R.id.piece_tray);
        for (int i = 0; i < tray.getChildCount(); i++) {
            View child = tray.getChildAt(i);
            if (child instanceof PieceTrayItemView slot) {
                if (slot.accepts(piece)) {
                    slot.setCount(slot.getCount() + 1);
                    return;
                }
            }
        }
    }

    /**
     * Maximum distance a piece may be re-snapped to the &#8474;[&#8730;2]
     * grid while centering a saved puzzle, without compromising its integrity.
     */
    private static final double SAVE_FUDGE_TOLERANCE = 0.125;

    /**
     * Save the current play field as a user puzzle.  Called back by
     * {@link SavePuzzleDialogFragment} once the user confirms, with the values
     * as entered; this finalizes (sanitizes) them and remembers the raw
     * entries so the dialog can pre-fill them for the next save.
     *
     * @param collection the collection name as entered
     * @param name the puzzle name as entered (not blank)
     * @param id the ID as entered (blank for the default)
     */
    @Override
    public void onSavePuzzle(@NonNull String collection,
                            @NonNull String name, @NonNull String id) {
        // Remember the raw entries to pre-fill the dialog next time.
        lastSaveCollection = collection;
        lastSaveName = name;
        lastSaveId = id;

        String dir = prefs.getUserPuzzlesDir();
        if (dir == null) {
            Log.w(LOG_TAG, "User puzzle directory has disappeared");
            showSaveError(getString(R.string.ErrorUserDirNotSet));
            return;
        }
        if (library == null)
            library = PuzzleLibrary.getInstance();

        // Finalize the entered values: a filename-safe collection (defaulting
        // to the resource hint), the puzzle name, and either the entered ID or
        // the default derived from the collection and name.
        String puzzleName = name.strip();
        String collectionName = PuzzleNaming.normalizeCollection(collection);
        if (collectionName.isEmpty())
            collectionName = PuzzleNaming.normalizeCollection(
                    getString(R.string.SaveDialogCollectionHint));
        String puzzleId = id.isBlank()
                ? PuzzleNaming.defaultId(collectionName, puzzleName)
                : PuzzleNaming.sanitizeId(id);

        // Build the independent, centered copy to save on the main thread
        // (cheap, and it reads the live play field).
        TangramPuzzle puzzle = playTableView.getPuzzle().clone();
        puzzle.setName(puzzleName);
        puzzle.setId(puzzleId);
        centerPuzzle(puzzle);

        // The Storage Access Framework work (resolving/creating the file and
        // writing it) can be slow, so do it off the main thread.
        final String fileName = getString(R.string.UserPuzzleFilePrefix)
                + collectionName + ".json";
        final Uri folderUri = Uri.parse(dir);
        BackgroundExecutor.runInBackground(
                () -> savePuzzleInBackground(puzzle, folderUri, fileName));
    }

    /**
     * Center a puzzle&rsquo;s pieces about the origin, re-aligning each to the
     * &#8474;[&#8730;2] grid where doing so barely moves it (the drop position
     * may not have landed on the cleanest coordinates).
     *
     * @param puzzle the puzzle to center in place
     */
    private void centerPuzzle(@NonNull TangramPuzzle puzzle) {
        TPoint centerAdjust = puzzle.getCenter().mirrorX().mirrorY();
        Log.d(LOG_TAG, String.format(Locale.US,
                "Adjusting puzzle center by %s", centerAdjust));
        for (TangramPiece piece : puzzle.getPieces()) {
            TPoint newCentroid = piece.getPosition().add(centerAdjust);
            TPoint reSnap = newCentroid.nearestQ2GridPoint();
            if (reSnap.distanceTo(newCentroid) < SAVE_FUDGE_TOLERANCE)
                newCentroid = reSnap;
            piece.setPosition(newCentroid);
        }
    }

    /**
     * Resolve the target file under the chosen directory and write the puzzle
     * to it, off the main thread.  Success reports via a toast and hides the
     * Save button; any failure is reported via {@link #showSaveError(String)}.
     *
     * @param puzzle the centered puzzle copy to save
     * @param folderUri the tree {@link Uri} of the puzzle directory
     * @param fileName the file name to save into
     */
    private void savePuzzleInBackground(@NonNull TangramPuzzle puzzle,
                                        @NonNull Uri folderUri,
                                        @NonNull String fileName) {
        DocumentFile saveFolder = DocumentFile.fromTreeUri(this, folderUri);
        // A persisted tree permission grants access to documents within it,
        // so canWrite() (permission-aware) is the check we want.
        if (saveFolder == null || !saveFolder.canWrite()) {
            Log.w(LOG_TAG, String.format(Locale.US,
                    "Permission to use %s has been revoked", folderUri));
            showErrorOnMain(getString(R.string.ErrorUserDirRevoked,
                    FileUtils.getFriendlyName(folderUri)));
            return;
        }
        DocumentFile saveFile = saveFolder.findFile(fileName);
        if (saveFile == null) {
            saveFile = saveFolder.createFile("application/json", fileName);
            if (saveFile == null) {
                String displayFullName = saveFolder.getName()
                        + File.separator + fileName;
                Log.e(LOG_TAG, String.format(Locale.US,
                        "Error creating file %s", displayFullName));
                showErrorOnMain(getString(
                        R.string.ErrorCannotCreateSaveFile, displayFullName));
                return;
            }
        }
        puzzle.setSourceFileName(saveFile.getName());
        try {
            library.savePuzzle(this, puzzle, saveFile);
        } catch (Exception e) {
            showErrorOnMain(getString(R.string.ErrorWritingPuzzle,
                    saveFile.getName(), e.getMessage()));
            return;
        }
        isFinished = true;
        final String savedName = puzzle.getName();
        final String savedFile = puzzle.getSourceFileName();
        runOnUiThread(() -> {
            Toast.makeText(this, getString(R.string.NotificationPuzzleSaved,
                    savedName, savedFile), Toast.LENGTH_LONG).show();
            // Hide the Save button, at least until the player changes the puzzle.
            saveButtonFrame.setVisibility(View.GONE);
        });
    }

    /** Post {@link #showSaveError(String)} to the main thread. */
    private void showErrorOnMain(String message) {
        runOnUiThread(() -> showSaveError(message));
    }

    /**
     * Show an error message after a failed save, and hide the Save button.
     *
     * @param message the message to display
     */
    private void showSaveError(String message) {
        saveButtonFrame.setVisibility(View.GONE);
        new AlertDialog.Builder(this)
                .setTitle(R.string.ErrorCannotSave)
                .setMessage(message)
                .setNegativeButton(R.string.SaveDialogButtonCancel, null)
                .setCancelable(true)
                .show();
    }

}
