/*
 * This class generated by Claude Code (Opus 4.8)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.xmission.trevin.android.tangram.ui;

import android.app.AlertDialog;
import android.content.Context;
import android.content.DialogInterface;
import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.util.Log;
import android.view.DragEvent;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.ImageButton;
import android.widget.LinearLayout;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.view.ContextThemeWrapper;
import androidx.core.content.IntentCompat;
import androidx.documentfile.provider.DocumentFile;

import com.xmission.trevin.android.tangram.R;
import com.xmission.trevin.android.tangram.data.*;
import com.xmission.trevin.android.tangram.util.FileUtils;

import java.io.File;
import java.util.Locale;

/**
 * The screen where the player actually assembles a Tangram.  It hosts a
 * {@link PlayTableView} for the play surface and a tray of
 * {@link PieceTrayItemView}s&mdash;one per kind of piece&mdash;from which
 * pieces can be dragged onto the surface.
 *
 * <p>This is not the launcher activity; it is started from the home
 * screen either for a chosen goal puzzle (via {@link #createIntent}) or
 * for free-play / sketch mode (with a {@code null} puzzle).</p>
 *
 * @author Claude Opus 4.8
 */
public class PlayActivity extends TangramActivity {

    private static final String LOG_TAG = "PlayActivity";

    /**
     * Intent extra carrying the goal puzzle.  Absent for free-play mode.
     */
    public static final String EXTRA_PUZZLE_GOAL =
            "com.xmission.trevin.android.tangram.PUZZLE_GOAL";

    private TangramPreferences prefs;

    private PlayTableView playTableView;

    private ViewGroup saveButtonFrame;

    /** Reference to the puzzle name toast if we show one, otherwise null */
    private Toast puzzleToast = null;

    private PuzzleLibrary library = null;

    /**
     * Build an intent to start this activity.
     *
     * @param context the launching context
     * @param goal    the goal puzzle to solve, or {@code null} for free play
     * @return the intent to hand to {@code startActivity}
     */
    @NonNull
    public static Intent createIntent(
            @NonNull Context context, @Nullable TangramPuzzle goal) {
        Intent intent = new Intent(context, PlayActivity.class);
        if (goal != null)
            intent.putExtra(EXTRA_PUZZLE_GOAL, goal);
        return intent;
    }

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        // TangramActivity applies the hint-level theme (piece colors) before
        // the content view is inflated.
        super.onCreate(savedInstanceState);
        Log.d(LOG_TAG, String.format(Locale.US,
                "onCreate(%s)", savedInstanceState == null ? "" : "saved state"));
        setContentView(R.layout.activity_play);
        WindowInsetsUtil.applySafeAreaPadding(this);

        prefs = TangramPreferences.getInstance(this);

        playTableView = findViewById(R.id.play_table);
        TangramPuzzle goal = IntentCompat.getParcelableExtra(
                getIntent(), EXTRA_PUZZLE_GOAL, TangramPuzzle.class);
        playTableView.setSolution(goal);
        setUpDropTarget();
        setUpOverlayControls(goal);
        configureTraySlots();

        // If we have a goal, show a temporary toast giving
        // the name of the puzzle.  This is chiefly used during
        // development to identify malformed puzzles.
        if (goal != null) {
            if (!goal.getName().isEmpty()) {
                Log.d(LOG_TAG, "Goal: " + goal.getName());
                puzzleToast = Toast.makeText(this,
                                goal.getName(), Toast.LENGTH_LONG);
                puzzleToast.show();
            } else {
                Log.d(LOG_TAG, "Unnamed goal provided:" + goal);
            }
        }
    }

    /**
     * Give each tray slot the play field&rsquo;s scale so a dragged piece
     * previews at the size it will have once dropped.
     */
    private void configureTraySlots() {
        ViewGroup tray = findViewById(R.id.piece_tray);
        for (int i = 0; i < tray.getChildCount(); i++) {
            View child = tray.getChildAt(i);
            if (child instanceof PieceTrayItemView)
                ((PieceTrayItemView) child).setUnitScaleProvider(
                        playTableView::getUnitScale);
        }
    }

    /**
     * Wire up the controls that hover over the play area: the back / exit
     * button, the goal preview (shown only when solving a puzzle), and the
     * contextual flip button (shown only while a flippable piece&mdash;the
     * parallelogram&mdash;is selected).
     *
     * @param goal the goal puzzle to display if any, or {@code null}
     * for free-play mode
     */
    private void setUpOverlayControls(@Nullable TangramPuzzle goal) {
        ViewGroup backFrame = findViewById(R.id.button_back_frame);
        moveControlToCorner(R.id.button_back_frame,
                prefs.getBackButtonCorner());
        findViewById(R.id.button_back).setOnClickListener((v) -> {
            if (puzzleToast != null)
                puzzleToast.cancel();
            finish();
        });

        ViewGroup goalFrame = findViewById(R.id.goal_view_frame);
        if (prefs.getHintLevel() != prefs.getPieceColoring()) {
            // Re-theme the goal view according to the hint level.
            goalFrame.removeAllViews();
            int hintTheme = resolveHintThemeResource();
            ContextThemeWrapper themedContext =
                    new ContextThemeWrapper(this, hintTheme);
            LayoutInflater inflater = getLayoutInflater()
                    .cloneInContext(themedContext);
            View themedGoal = inflater.inflate(
                    R.layout.goal_frame, goalFrame, true);
        }
        moveControlToCorner(R.id.goal_view_frame, prefs.getGoalCorner());
        TangramPuzzleView goalView = findViewById(R.id.goal_view);
        if (goal != null) {
            goalView.setPuzzle(goal);
            goalFrame.setVisibility(View.VISIBLE);
        } else {
            goalFrame.setVisibility(View.GONE);
        }

        final ViewGroup flipFrame = findViewById(R.id.button_flip_frame);
        ImageButton flipButton = findViewById(R.id.button_flip);
        flipButton.setOnClickListener(v -> playTableView.flipSelectedPiece());
        playTableView.setOnSelectionChangedListener(selected ->
                flipFrame.setVisibility(canFlip(selected)
                        ? View.VISIBLE : View.GONE));
        // Reflect the current selection (normally none on a fresh start).
        flipFrame.setVisibility(
                canFlip(playTableView.getSelectedPiece())
                        ? View.VISIBLE : View.GONE);

        saveButtonFrame = findViewById(R.id.button_save_frame);
        moveControlToCorner(R.id.button_save_frame,
                prefs.getSaveButtonCorner());
        // We only care about saving *if* we're in free-play mode
        // and *if* the user has set up a directory for user puzzles.
        if ((goal == null) && (prefs.getUserPuzzlesDir() != null)) {
            ImageButton saveButton = findViewById(R.id.button_save);
            saveButton.setOnClickListener(new SavePuzzleListener());
        }
    }

    /**
     * Move a given hover control into the designated corner.
     *
     * @param groupId the ID of the {@link LinearLayout} containing the control
     * @param corner the corner in which to move the layout
     */
    private void moveControlToCorner(
            int groupId,
            @NonNull TangramPreferences.Corner corner) {
        LinearLayout frame = findViewById(groupId);
        FrameLayout.LayoutParams params =
                (FrameLayout.LayoutParams) frame.getLayoutParams();
        params.gravity = corner.getGravity();
        frame.setLayoutParams(params);
    }

    /** @return whether a (possibly {@code null}) piece can be flipped. */
    private static boolean canFlip(@Nullable TangramPiece piece) {
        return piece != null && piece.canFlip();
    }

    /**
     * Make the play surface accept pieces dropped from the tray, creating
     * a fresh piece there and decrementing that kind&rsquo;s tray count.
     */
    private void setUpDropTarget() {
        playTableView.setOnDragListener((view, event) -> {
            switch (event.getAction()) {
                case DragEvent.ACTION_DRAG_STARTED:
                case DragEvent.ACTION_DRAG_ENTERED:
                case DragEvent.ACTION_DRAG_LOCATION:
                case DragEvent.ACTION_DRAG_EXITED:
                case DragEvent.ACTION_DRAG_ENDED:
                    return true;

                case DragEvent.ACTION_DROP:
                    Object state = event.getLocalState();
                    if (state instanceof PieceTrayItemView slot) {
                        if (slot.getCount() > 0) {
                            TangramPiece piece = slot.createPiece();
                            playTableView.addPieceAtViewLocation(
                                    piece, event.getX(), event.getY());
                            slot.decrement();
                        }
                    }
                    return true;

                default:
                    return false;
            }
        });

        // A piece dragged off the field comes back to its tray slot.
        playTableView.setOnPieceReturnedListener(this::returnPieceToTray);
    }

    /**
     * Return a piece that was dragged off the play field to its tray slot,
     * bumping that slot&rsquo;s available count back up.
     *
     * @param piece the piece that left the field
     */
    private void returnPieceToTray(@NonNull TangramPiece piece) {
        ViewGroup tray = findViewById(R.id.piece_tray);
        for (int i = 0; i < tray.getChildCount(); i++) {
            View child = tray.getChildAt(i);
            if (child instanceof PieceTrayItemView slot) {
                if (slot.accepts(piece)) {
                    slot.setCount(slot.getCount() + 1);
                    return;
                }
            }
        }
    }

    /**
     * Called when the user clicks the save button.
     */
    private class SavePuzzleListener implements View.OnClickListener {
        private final SavePuzzleCallback callback = new SavePuzzleCallback();
        private AlertDialog saveDialog = null;
        @Override
        public void onClick(View v) {
            if (saveDialog == null) {
                saveDialog = new AlertDialog.Builder(PlayActivity.this)
                        .setTitle(R.string.SaveDialogTitle)
                        .setView(R.layout.dialog_save_puzzle)
                        .setPositiveButton(R.string.SaveDialogButtonSave,
                                // MUST pass null here to prevent Android from
                                // closing the dialog before the save is finished.
                                null)
                        .setNegativeButton(R.string.SaveDialogButtonCancel,
                                (d, w) -> d.dismiss())
                        .create();
                saveDialog.getButton(DialogInterface.BUTTON_POSITIVE)
                        .setOnClickListener(callback);
                saveDialog.setOnShowListener((d) -> {
                    saveDialog.setCancelable(true);
                    saveDialog.setCanceledOnTouchOutside(false);
                    saveDialog.getButton(DialogInterface.BUTTON_POSITIVE)
                            .setEnabled(true);
                    saveDialog.getButton(DialogInterface.BUTTON_NEGATIVE)
                            .setEnabled(true);
                });
            }
            saveDialog.show();
        }

        /**
         * Called when the user clicks "Save" in the save dialog.
         */
        private class SavePuzzleCallback implements View.OnClickListener {
            @Override
            public void onClick(View button) {
                // Disable dismissing the dialog until we're done with it.
                saveDialog.getButton(DialogInterface.BUTTON_POSITIVE)
                        .setEnabled(false);
                saveDialog.getButton(DialogInterface.BUTTON_NEGATIVE)
                        .setEnabled(false);
                saveDialog.setCancelable(false);

                EditText categoryEdit =
                        saveDialog.findViewById(R.id.SaveDialogCategory);
                EditText nameEdit =
                        saveDialog.findViewById(R.id.SaveDialogName);
                EditText idEdit =
                        saveDialog.findViewById(R.id.SaveDialogID);
                String category = categoryEdit.getText().toString().strip();
                String name = nameEdit.getText().toString().strip();
                String id = idEdit.getText().toString().strip();

                // Convert any unsafe filename characters to '_'
                // FIXME: Should also allow non-ASCII alpha characters
                category.replaceAll("[^-.0-9A-Z_a-z]", "_")
                        .replaceFirst("^[-._]+", "")
                        .replaceFirst("[-._]+$", "");
                if (category.isEmpty())
                    category = getString(R.string.SaveDialogCategoryHint);

                if (id.isEmpty()) {
                    // By default, set the ID to the category plus
                    // the name with spaces replaced by dashes.
                    id = (category + "-" + name).replaceAll(" ", "-");
                }
                // Ensure the ID only has valid characters
                // FIXME: Should also allow non-ASCII alpha characters
                id.replaceAll("[^-.0-9A-Z_a-z]", "_");
                if (id.matches("[-.0-9].*"))
                    id = "_" + id;

                String dir = prefs.getUserPuzzlesDir();
                // Sanity check
                if (dir == null) {
                    Log.w(LOG_TAG, "User puzzle directory has disappeared");
                    showError(getString(R.string.ErrorUserDirNotSet));
                    return;
                }
                Uri folderUri = Uri.parse(dir);
                DocumentFile saveFolder = DocumentFile.fromTreeUri(
                        PlayActivity.this, folderUri);
                // Verify we still have access to this directory
                if (!FileUtils.isDirectoryAccessible(
                        PlayActivity.this, folderUri)) {
                    Log.w(LOG_TAG, String.format(Locale.US,
                            "Permission to use %s has been revoked", dir));
                    showError(getString(R.string.ErrorUserDirRevoked,
                            saveFolder.getName()));
                    return;
                }
                String fileName = getString(R.string.UserPuzzleFilePrefix)
                        + category + ".json";
                DocumentFile saveFile = saveFolder.findFile(fileName);
                if (saveFile == null) {
                    saveFile = saveFolder.createFile(
                            "application/json", fileName);
                    if (saveFile == null) {
                        String displayFullName = saveFolder.getName()
                                + File.separator + fileName;
                        Log.e(LOG_TAG, String.format(Locale.US,
                                "Error creating file %s", displayFullName));
                        showError(getString(R.string.ErrorCannotCreateSaveFile,
                                displayFullName));
                        return;
                    }
                }

                if (library == null)
                    library = PuzzleLibrary.getInstance();

                TangramPuzzle puzzle = playTableView.getPuzzle().clone();
                puzzle.setSourceFileName(saveFile.getName());
                puzzle.setName(name);
                puzzle.setId(id);

                // Center the puzzle.
                TPoint centerAdjust = puzzle.getCenter().mirrorX().mirrorY();
                for (TangramPiece piece : puzzle.getPieces()) {
                    piece.setPosition(piece.getPosition().add(centerAdjust));
                }
                // Save it.
                try {
                    library.savePuzzle(PlayActivity.this, puzzle, saveFile);
                } catch (Exception e) {
                    showError(getString(R.string.ErrorWritingPuzzle,
                            saveFile.getName(), e.getMessage()));
                    return;
                }
                saveDialog.dismiss();
                return;
            }

            /**
             * Show an error message if we fail to save the puzzle.
             * This also dismisses the save dialog and hides the Save
             * button.
             *
             * @param message the message to display
             */
            void showError(String message) {
                saveDialog.dismiss();
                saveButtonFrame.setVisibility(View.GONE);
                new AlertDialog.Builder(PlayActivity.this)
                        .setTitle(R.string.ErrorCannotSave)
                        .setMessage(message)
                        .setNegativeButton(
                                R.string.SaveDialogButtonCancel, null)
                        .setCancelable(true)
                        .show();
            }
        }

    }

}
