/*
 * This class generated by Claude Code (Opus 4.8)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.xmission.trevin.android.tangram.ui;

import android.app.Dialog;
import android.content.Context;
import android.os.Bundle;
import android.text.Editable;
import android.text.InputFilter;
import android.text.Spanned;
import android.text.TextWatcher;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.app.AlertDialog;
import androidx.fragment.app.DialogFragment;

import com.xmission.trevin.android.tangram.R;
import com.xmission.trevin.android.tangram.util.PuzzleNaming;

/**
 * The &ldquo;Save Puzzle&rdquo; dialog, shown as a {@link DialogFragment}.
 * It collects the collection name, puzzle name, and (optional) ID, restricting
 * each field to legal characters as they are typed and previewing the default
 * ID in the ID field&rsquo;s hint.  When the user confirms, it hands the
 * finalized values back to the host activity (which owns the actual save) via
 * {@link OnSavePuzzleListener}.
 *
 * <p>Because the layout is inflated here (rather than through
 * {@code AlertDialog.Builder.setView(int)}), the field views exist immediately,
 * so the input filters and text watcher can be installed without waiting for
 * the dialog to be shown.</p>
 *
 * @author Claude Opus 4.8
 */
public class SavePuzzleDialogFragment extends DialogFragment {

    /** Tag identifying this fragment within the {@code FragmentManager}. */
    public static final String TAG = "SavePuzzle";

    private static final String ARG_COLLECTION = "collection";
    private static final String ARG_NAME = "name";
    private static final String ARG_ID = "id";

    /**
     * Callback through which the values the user entered are handed to the
     * host, which finalizes (sanitizes) and saves them&mdash;and remembers
     * them to pre-fill the dialog next time.
     */
    public interface OnSavePuzzleListener {
        /**
         * @param collection the collection name as entered
         * @param name the puzzle name as entered (not blank)
         * @param id the ID as entered (may be blank for the default)
         */
        void onSavePuzzle(@NonNull String collection,
                          @NonNull String name, @NonNull String id);
    }

    /**
     * Create the dialog with the given fields pre-filled (e.g. the values
     * from the previous save this session).
     *
     * @param collection the collection field's initial text
     * @param name the puzzle-name field's initial text
     * @param id the ID field's initial text
     * @return the configured fragment
     */
    @NonNull
    public static SavePuzzleDialogFragment newInstance(
            @NonNull String collection, @NonNull String name,
            @NonNull String id) {
        SavePuzzleDialogFragment fragment = new SavePuzzleDialogFragment();
        Bundle args = new Bundle();
        args.putString(ARG_COLLECTION, collection);
        args.putString(ARG_NAME, name);
        args.putString(ARG_ID, id);
        fragment.setArguments(args);
        return fragment;
    }

    @Nullable
    private OnSavePuzzleListener listener;

    private AlertDialog dialog;
    private EditText collectionEdit;
    private EditText nameEdit;
    private EditText idEdit;

    @Override
    public void onAttach(@NonNull Context context) {
        super.onAttach(context);
        if (context instanceof OnSavePuzzleListener)
            listener = (OnSavePuzzleListener) context;
    }

    @NonNull
    @Override
    public Dialog onCreateDialog(@Nullable Bundle savedInstanceState) {
        View content = requireActivity().getLayoutInflater()
                .inflate(R.layout.dialog_save_puzzle, null, false);
        collectionEdit = content.findViewById(R.id.SaveDialogCollection);
        nameEdit = content.findViewById(R.id.SaveDialogName);
        idEdit = content.findViewById(R.id.SaveDialogID);

        // Restrict each field to its legal character set as the user types.
        // Positional constraints (start character, trimming) are applied when
        // the values are finalized, not here.
        collectionEdit.setFilters(new InputFilter[] {
                new AllowedCharactersFilter(true) });
        idEdit.setFilters(new InputFilter[] {
                new AllowedCharactersFilter(false) });

        // Pre-fill from the arguments only on first creation; on a
        // configuration change the fields restore their own edited text.
        Bundle args = getArguments();
        if (savedInstanceState == null && args != null) {
            collectionEdit.setText(args.getString(ARG_COLLECTION, ""));
            nameEdit.setText(args.getString(ARG_NAME, ""));
            idEdit.setText(args.getString(ARG_ID, ""));
        }

        NamesWatcher watcher = new NamesWatcher();
        collectionEdit.addTextChangedListener(watcher);
        nameEdit.addTextChangedListener(watcher);
        updateIdHint();

        dialog = new AlertDialog.Builder(requireContext())
                .setTitle(R.string.SaveDialogTitle)
                .setView(content)
                // Null listener: the positive button is overridden in
                // onShow so it validates without auto-dismissing.
                .setPositiveButton(R.string.SaveDialogButtonSave, null)
                .setNegativeButton(R.string.SaveDialogButtonCancel,
                        (d, which) -> d.dismiss())
                .create();
        dialog.setOnShowListener(d -> {
            dialog.setCanceledOnTouchOutside(false);
            dialog.getButton(AlertDialog.BUTTON_POSITIVE)
                    .setOnClickListener(v -> onSaveClicked());
            updateSaveEnabled();
        });
        return dialog;
    }

    /** Recompute the default-ID hint and Save-button state after an edit. */
    private void afterNamesChanged() {
        updateIdHint();
        updateSaveEnabled();
    }

    /** Show, as the ID field's hint, the default ID that would be used. */
    private void updateIdHint() {
        String collection = effectiveCollection();
        String name = nameEdit.getText().toString().strip();
        if (name.isEmpty())
            name = getString(R.string.SaveDialogNameHint);
        idEdit.setHint(PuzzleNaming.defaultId(collection, name));
    }

    /** Save is allowed only once the puzzle has a (non-blank) name. */
    private void updateSaveEnabled() {
        if (dialog == null)
            return;
        Button save = dialog.getButton(AlertDialog.BUTTON_POSITIVE);
        if (save != null)
            save.setEnabled(!nameEdit.getText().toString().isBlank());
    }

    /**
     * @return the normalized collection name, or the default from resources
     * if the field is left blank
     */
    @NonNull
    private String effectiveCollection() {
        String collection = PuzzleNaming.normalizeCollection(
                collectionEdit.getText().toString());
        if (collection.isEmpty())
            collection = PuzzleNaming.normalizeCollection(
                    getString(R.string.SaveDialogCollectionHint));
        return collection;
    }

    /** Hand the entered values to the host to finalize and save. */
    private void onSaveClicked() {
        if (nameEdit.getText().toString().isBlank())
            return; // Save should be disabled, but guard anyway.
        if (listener != null)
            listener.onSavePuzzle(collectionEdit.getText().toString(),
                    nameEdit.getText().toString(),
                    idEdit.getText().toString());
        dismiss();
    }

    /**
     * Restricts input to the characters allowed in a collection name or ID:
     * letters (including non-Latin), digits, {@code '-'}, {@code '.'},
     * {@code '_'}, and&mdash;for a collection&mdash;whitespace.  Other
     * characters are dropped.
     */
    private static final class AllowedCharactersFilter implements InputFilter {
        private final boolean allowWhitespace;

        AllowedCharactersFilter(boolean allowWhitespace) {
            this.allowWhitespace = allowWhitespace;
        }

        @Override
        public CharSequence filter(CharSequence source, int start, int end,
                                   Spanned dest, int dstart, int dend) {
            StringBuilder kept = new StringBuilder(end - start);
            boolean changed = false;
            for (int i = start; i < end; ) {
                int codePoint = Character.codePointAt(source, i);
                int width = Character.charCount(codePoint);
                if (isAllowed(codePoint))
                    kept.appendCodePoint(codePoint);
                else
                    changed = true;
                i += width;
            }
            // Returning null accepts the original text unchanged.
            return changed ? kept.toString() : null;
        }

        private boolean isAllowed(int codePoint) {
            return Character.isLetterOrDigit(codePoint)
                    || codePoint == '-' || codePoint == '.' || codePoint == '_'
                    || (allowWhitespace && Character.isWhitespace(codePoint));
        }
    }

    /** Updates the default-ID hint and Save state as names are edited. */
    private final class NamesWatcher implements TextWatcher {
        @Override
        public void beforeTextChanged(CharSequence s,
                                      int start, int count, int after) {
        }

        @Override
        public void onTextChanged(CharSequence s,
                                  int start, int before, int count) {
        }

        @Override
        public void afterTextChanged(Editable s) {
            afterNamesChanged();
        }
    }
}