/*
 * This class generated by Claude Code (Opus 4.8)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.xmission.trevin.android.tangram.util;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Unit tests for {@link PuzzleNaming}.
 *
 * @author Claude Opus 4.8
 */
public class PuzzleNamingTests {

    @Test
    public void testNormalizeCollection() {
        assertEquals("My_Set", PuzzleNaming.normalizeCollection("My Set"));
        assertEquals("My_Set", PuzzleNaming.normalizeCollection("  My Set  "));
        // Leading/trailing whitespace, '.', and '-' are stripped...
        assertEquals("Set", PuzzleNaming.normalizeCollection("-.Set.-"));
        // ...but a leading underscore (a valid start) is kept.
        assertEquals("_Set", PuzzleNaming.normalizeCollection("_Set"));
        // Internal '-' and '.' are kept.
        assertEquals("a-b.c", PuzzleNaming.normalizeCollection("a-b.c"));
        assertEquals("", PuzzleNaming.normalizeCollection("   "));
        assertEquals("", PuzzleNaming.normalizeCollection(null));
    }

    @Test
    public void testDisplayCollection() {
        assertEquals("My Set", PuzzleNaming.displayCollection("My_Set"));
        assertEquals("", PuzzleNaming.displayCollection(null));
    }

    @Test
    public void testNormalizeNameForId() {
        assertEquals("my-shape", PuzzleNaming.normalizeNameForId("My Shape"));
        assertEquals("my-shape", PuzzleNaming.normalizeNameForId("  My   Shape  "));
        // Lower-cased, disallowed dropped, leading/trailing non-alnum trimmed.
        assertEquals("foo", PuzzleNaming.normalizeNameForId(".Foo."));
        assertEquals("a-b", PuzzleNaming.normalizeNameForId("a (b)"));
        assertEquals("", PuzzleNaming.normalizeNameForId("!!!"));
    }

    @Test
    public void testDefaultId() {
        assertEquals("default-my-shape",
                PuzzleNaming.defaultId("default", "My Shape"));
        assertEquals("_Set", PuzzleNaming.normalizeCollection("_Set"));
        assertEquals("_Set-my-shape",
                PuzzleNaming.defaultId("_Set", "My Shape"));
        // A collection starting with a digit forces a leading underscore.
        assertEquals("_2048-game",
                PuzzleNaming.defaultId("2048", "Game"));
    }

    @Test
    public void testSanitizeId() {
        // Mixed case preserved; no collection/name substitutions.
        assertEquals("MyPuzzle_1", PuzzleNaming.sanitizeId("MyPuzzle_1"));
        // Disallowed characters dropped.
        assertEquals("abc", PuzzleNaming.sanitizeId("a b/c"));
        // Must start with a letter or underscore.
        assertEquals("_2thing", PuzzleNaming.sanitizeId("2thing"));
        assertEquals("_-dash", PuzzleNaming.sanitizeId("-dash"));
        assertEquals("_okay", PuzzleNaming.sanitizeId("_okay"));
        assertEquals("", PuzzleNaming.sanitizeId(""));
    }

    @Test
    public void testEnsureNcNameStart() {
        assertEquals("letter", PuzzleNaming.ensureNcNameStart("letter"));
        assertEquals("_under", PuzzleNaming.ensureNcNameStart("_under"));
        assertEquals("_9lives", PuzzleNaming.ensureNcNameStart("9lives"));
        assertEquals("", PuzzleNaming.ensureNcNameStart(""));
    }
}